/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Aspects': '相位',
    'Aspect Points': '相位点',
//    'Prospit': '赞成',
//    'Derse': '德赛',
    'Class': '阶级',
    'Class Points': '阶级点',
    'Loading...': '加载中...',
    'Play Again': '重玩',
    'points': '点数',
    'Genesis -': '创世记-',
    'Keep Going': '继续',
    'Offline Time': '离线时间',
    'Multipliers': '倍数',
    'Time Power': '时间力量',
    'Currently': '当前',
    "Time Multipliers": "时间加倍器",
    'Absorb +': '重置 +',
    'Space Power': '空间力量',
    'Next at': '下一个需要',
    'The Modding Tree\n							Discord': 'The Modding Tree\n							Discord',
    'Milestones': '里程碑',
    'BLESSING OF LIFE': '生命的祝福',
    'Upgrades': '升级',
    'Mind Power': '精神力量',
    'Heart Power': '心灵力量',
    "Space Generator": "空间发生器",
    "Space Generator\^2": "空间发生器^2",
    "Space Generator\^3": "空间发生器^3",
    "Space Generator\^4": "空间发生器^4",
    "Space Generator\^5": "空间发生器^5",
    'Hope Essence': '希望精华',
    'Hope Power': '希望力量',
    'Challenges': '挑战',
    'Completed': '已完成',
    'Exit Early': '提前退出',
    'Finish': '完成',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Shard and Essence replacements scales better.': '碎片和精华替代品可更好地扩展。',
    'Unlocks special milestones for each of the Lunar Sway (Derse & Prospit) layers.': '解锁每个月球摇摆(Derse & proit)层的特殊里程碑。',
    'Unlocks Derse.': '解锁 Derse.',
    'Unlocks Prospit.': '解锁 Prospit.',
    'Boosts all of the second upgrade row effect, based on Aspect Points, including the above upgrade\'s effect.': '根据相位点增强所有第二个升级行效果，包括上述升级的效果。',
    'Keeps Space Upgrades on Breath and Blood resets.': '在呼吸和血液重置时保持空间升级。',
    'Keeps Rage, Hope, Mind and Heart milestones plus Mind and Heart upgrades on Breath and Blood resets.': '保持愤怒，希望，精神和心脏的里程碑，并在重置呼吸和血液时保持精神和心脏的升级。',
    'Keeps Light, Void, Life and Doom milestones on Breath and Blood resets.': '在呼吸和血液重置时保持光明，虚空，生命和厄运的里程碑。',
    'Keeps Hope Upgrades and Rage Milestones on Breath and Blood resets.': '在呼吸和血液重置上保持希望升级和狂暴里程碑。',
    'Absorbing Breath and Blood Essence no longer resets anything.': '呼吸和血液的重置不再重置任何东西。',
    'Automatically do Breath and Blood resets.': '自动执行呼吸和血液重置。',
    'Gain the ability to bulk get Time Boosters. Also affects autobuyers.': '获得批量获取时间推进器的能力。 也影响自动购买者。',
    'Keeps Doom Wraths on Breath and Blood resets.': '使末日之怒重置于呼吸和鲜血状态。',
    'Progression': '进阶',
    'Multiplies all of the second upgrade row effect with the fourth root of Skaia level plus 1, after all above power upgrades.': '在以上所有能力升级之后，将所有第二个升级行效果乘以Skaia等级的第四个根再加上1。',
    'You can bulk absorb Breath and Blood ': '你可以批量重置呼吸和血液',
    'Prospit is currently having': 'Prospit点当前有',
    'Not yet implemented.': '尚未实现。',
    'Signs Viewer': '标志查看器',
    'Derse is currently having': 'Derse目前拥有',
    'Currently: ×': '当前: ×',
    'Doubles the Time Shards and Time Essence replacement value.': '将时间碎片和时间精华替换值加倍。',
    'Filling the Echebar gives you 100 levels instead of 1.': '填充回切条可以让你升100级而不是1级。',
    'Current effects': '目前的效果',
    'Classes': '阶级',
    'Class Points': '阶级点',
    'All Rust sign effects boosts Class Point gain.': '所有锈迹效果都可以提高阶级点获取。',
    'Abolish your aspect and class progress to get +': '取消您的相位和阶级进度以获取+',
    'All Bronze sign effects boosts all Aspect Point effects.': '所有青铜符号效果提升所有相位点效果。',
    'All Aspect Powers are procedually generated instead of bought.': '所有相位力量都是程序生成的，而不是购买的。',
    'Active': '激活',
    'A NEW AGE': '新时代',
    'Gemcen': '金森',
    'Note: Autobuyers only fire once per second due to performance issues.': '注意：由于性能问题，自动购买者每秒只能触发一次。',
    'Void': '虚空',
    'Light': '光明',
    'Shards': '碎片',
    'Power': '力量',
    'Essence': '精华',
    'Doom': '厄运',
    'Breath': '呼吸',
    'Blood': '血液',
    'Time': '时间',
    'Space': '空间',
    'Rage': '愤怒',
    'Mind': '精神',
    'Life': '生命',
    'Hope': '希望',
    'Heart': '心灵',
    'You currently have': '你当前有',
    'Unlocks Classes': '解锁阶级',
    'Skaia is currently in level': '斯卡亚现在处于水平状态',
    'Meta': '元',
    'Echepoints': '回切点',
    'made by ducdat': '由ducdat制作',
    'BUT WHY THOUGH': '但是为什么要思想',
    'T: Absorb Time Power': 'T: 吸取时间的力量',
    'server of the person who made the original game': '最初的游戏制作者的服务器',
    'Homosuck': '绿帽色',
    'Aqua': '水色',
    'NEVER': '从不',
    'INCOMPLETE': '部分',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'ALWAYS': '一直',
    'SHOWN': '显示',
    'ON': '开启',
    'OFF': '关闭',
    'Default': '默认',
    'Export to clipboard': '导出到剪贴板',
    'UNDEFINED': '未定义',
    'Save': '保存',
    'Import': '导入',
    'HARD RESET': '硬重置',
    'The Prestige Tree Modfinder': '声望树修改器',
    'Changelog': '更新日志',
    'Acknowledgements': '鸣谢',
    'a mod of The Prestige Tree made by Jacorb and Aarex': 'Jacorb和Aarex制作的The Prestige Tree的mod',
    'wall of text saying I do not own most of this': '文字墙说我不拥有大部分',
    'using The Modding Tree': '使用改装树',
    'This is made entirely for entertainment and parody purposes, no income is generated from this nor it\'s made to steal anybody\'s original works.': '这完全是出于娱乐和模仿目的而制作的，因此不会产生任何收入，也不会窃取任何人的原创作品。',
    'suggest everything and talk about how bad this mod is here': '建议一切并谈论这个mod有多糟糕',
    'in case you\'re already sick of this': '万一你已经厌倦了这个',
    'see what happened throughout this thing\'s history': '看看这件事的历史发生了什么',
    'Hotkeys': '快捷键',
    'Time Boosters': '时间增强器',
    'Beginner tip: Hold T to automatically absorb Time Power': '初学者提示：按住T可自动转生获得时间力量',
    'You have': '你有',
    'The Prestreestuck': '创世声望树',
    'The Modding Tree Discord': '改装树Discord',
    'The game is currently being updated.': '游戏正在更新中。',
    'Please check the Discord to see if there are new content updates!': '请检查Discord，看看是否有新的内容更新！',
    'Main Prestige Tree server': '主声望树服务器',
    'Time Power boosts point gain.': '时间力量加成点数获取。',
    'You total amount of Time Multipliers boosts your point gain.': '根据你拥有的时间加倍器总数加成你的点数获取。',
    'Space Power boosts Time Power gain.': '空间力量加成时间力量获得量。',
    'Add another Time Booster that reduces the price of the previous one.': '增加一个额外的时间增强器，它也可以降低前一个时间增强器的价格。',
    'Mind Power boosts Time Power gain.': '精神力量加成时间力量获得量。',
    'Heart Power boosts Time Power gain.': '心灵力量加成时间力量获得量。',
    "Space Accelerator": "空间加速器",
    'Points boost point gain.': '点数加成点数获得量。',
    'Gain 10% of your Time Power gain on absorb per second.': '每秒获得10%当前转生可获得的时间力量。',
    'Your Space Power gain on absorb boosts point gain.': '重置可获得空间力量加成点数获取',
    'Automatically max-upgrades your Time Multipliers for you every tick.': '每一刻都会自动购买所有时间加倍器。',
    'Adds upgrades to the Time layer': '在时间层级内增加新的升级。',
    "Automatically get Time Boosters for you every tick.": "每一刻都会自动购买时间增强器。 ",
    'Unspent Space Power boosts point gain.': '未使用的空间力量加成点数获得量。',
    'Faster Time Power generation based on Space Power.': '根据空间力量加速时间力量获取。',
    'Time Power boosts Space Power gain.': '时间力量加成空间力量获得量。',
    'Autobuyer prioritizes later Time Multipliers instead of earlier ones.': '自动购买者购买时间加倍器时倾向于先购买后面的。',
    '\^1.08 all Time Boosters effect.': '^1.08所有时间增强器效果。',
    'Autobuyer prioitizes Time Boosters instead of Time Multipliers.': '自动购买者倾向于先购买时间增强器而不是加倍器。',
    'Adds more upgrades to the Time layer.': '在时间层级内增加更多新的升级。',
    'Buys 1 of each Space Generators and Space Accelerators per tick.': '每一刻自动购买每一个空间发生器和加速器。',
    'Automatically buys Time upgrades.': '自动购买时间升级。',
    'Automatically get Time Booster\^2s.': '自动购买时间增强器^2。',
    'You keep your 2nd, 4th, 6th, 8th, 10th, and 12th Space upgrades on Mind Power absorb.': '精神重置后你可以保留第2，4，6，8，10，12项空间升级',
    'You keep your 1st, 3nd, and 5th Space upgrades on Mind Power absorb.': '精神重置后你可以保留第1，3，5项空间升级',
    'You keep your 7th, 9th, and 11th Space upgrades on Mind Power absorb.': '精神重置后你可以保留第7，9，11项空间升级',
    'Gain 5% of your Space Power gain on absorb per second.': '每秒获得空间重置可获得的5%空间力量',
    'You keep your forth row of Space upgrades on Mind Power absorb.': '精神重置后你可以保留第四排空间升级',
    'Unlocks Mind Upgrades.': '解锁精神升级',
    'Gain 5% of your Mind Power gain on absorb per second.': '每秒获得精神重置可获得的5%精神力量',
    'Mind Power boost point gain.': '心灵力量加成点数获得量',
    'Mind Power boost Time Power gain.': '心灵力量加成时间力量获得量',
    'Mind Power boost Space Power gain.': '心灵力量加成空间力量获得量',
    'Mind Power boosts all Space Generators.': '心灵力量加成所有空间发生器',
    'Getting Time Boosters no longer resets anything.': '购买时间增强器不再重置任何东西',
    'Multiplier from Time Boosters boosts point gain.': '时间增强器提供的加倍器加成点数',
    'Time Booster\^2s no longer resets, and its multi boosts Time Power gain.': '时间增强器^2不再重置，并且它还会加成时间力量',
    'which are boosting point gain by ×e': '可以加成点数获得量 ×e',
    'which are boosting Mind Power gain by ×e': '可以加成精神力量获得量 ×e',
    'which are boosting Heart Power gain by ×e': '可以加成心灵力量获得量 ×e',
    'Points boost Heart Power gain.': '点数加成心灵力量获得量',
    'Time Power boosts Heart Power gain.': '时间力量加成心灵力量获得量',
    'Space Power boosts Heart Power gain.': '空间力量加成心灵力量获得量',
    'Space boosts Heart Power gain.': '空间加成心灵力量获得量',
    'Time Generators and Space Multipliers don\'t take anything away.': '时间加倍器和空间发生器不再消耗任何东西',
    'You keep your 1st, 3rd, and 5th Space upgrade on Heart Power absorb.': '心灵重置后你可以保留第1，3，5项空间升级',
    'You keep your 7th, 9th, and 11th Space upgrade on Heart Power absorb.': '心灵重置后你可以保留第7，9，11项空间升级',
    'You keep your 2nd, 4th, 6th, 8th, 10th, and 12th Space upgrade on Heart Power absorb.': '心灵重置后你可以保留第2，4，6，8，10，12项空间升级',
    'You keep your fourth row of Space upgrades on Heart Power absorb.': '心灵重置后你可以保留第四排空间升级',
    'Unlocks Heart Upgrades.': '解锁心灵升级',
    'Gain 5% of your Heart Power gain on absorb per second.': '每秒获得心灵重置可获得的5%心灵力量',
    'Buying an upgrade increases the cost of the upgrades in the same row.': '购买任意一项升级会提升同行其它升级的价格',
    'Buying Time Gens and Accelerators buys max instead of buy once. Also affects autobuyers.': '购买时间生产和加速可以最大购买，对自动购买也有效',
    'You need to buy at least one upgrade in the upper row before you can buy upgrades at that row.': '你必须至少购买一个上一行的升级才能购买下一行的升级',
    'Respecing Hope Upgrades does not give your Hope Power back!': '重置希望升级并不会返还心灵力量！',
    'Respec Hope Upgrades': '重置希望升级',
    'Points decrease the requirements for Hope and Rage resets.': '点数降低希望和愤怒的重置需求',
    'The upgrade above boosts point gain.': '上方升级也加成点数获得量',
    'The upgrade above boosts Time Power gain.': '上方升级也加成时间力量获得量',
    'The upgrade above boosts Space Power gain.': '上方升级也加成空间力量获得量',
    'Hope and Rage Essence boosts Mind and Heart Power gain.': '希望和愤怒精华加成心灵和精神力量获得量',
    'Hope and Rage Essence boosts Space Power gain.': '希望和愤怒精华加成空间力量获得量',
    'Hope and Rage Essence boosts Time Power gain.': '希望和愤怒精华加成时间力量获得量',
    'Hope and Rage Essence boosts point gain.': '希望和愤怒精华加成点数获得量',
    'Reduces the Hope Essence requirements by 1e12.': '希望精华需求降低1e12',
    'Reduces the Rage Essence requirements by 1e10.': '希望精华需求降低1e10',
    'Void Power boosts Light Power gain': '虚空力量加成光明力量获得量',
    'Light Power boosts Void Power gain': '光明力量加成虚空力量获得量',
    'Light Power and Void Power boosts point gain': '光明力量和虚空力量加成点数获得量',
    'Gets all Space upgrades and the first six Mind\/Heart milestones on Hope reset.': '希望重置后你可以保留所有空间升级和前六个心灵/精神里程碑',
    'Unlocks Hope upgrades.': '解锁希望升级',
    'Gives you all Heart and Mind upgrades and their seventh milestone on Hope reset.': '希望重置后你可以保留所有心灵/精神升级和它们的第七个里程碑',
    'Automatically do Rage resets.': '自动进行愤怒重置',
    'Gets all Space upgrades and the first six Mind\/Heart milestone on Rage reset.': '愤怒重置后你可以保留所有空间升级和前六个心灵/精神里程碑',
    'Unlocks Rage challenges.': '解锁愤怒挑战',
    'Gives you all Heart and Mind upgrades and their seventh milestone on Rage reset.': '愤怒重置后你可以保留所有心灵/精神升级和它们的第七个里程碑',
    'Automatically do Hope resets.': '自动进行希望重置',
    'Points decrease the requirement for Rage Essence and Hope Essence absorb.': '点数降低愤怒精华和希望精华的重置需求',
    'Rage Essence and Hope Essence boosts Time Power gain.': '愤怒精华和希望精华加成时间力量获得量',
    'Rage Essence and Hope Essence boosts Space Power gain.': '愤怒精华和希望精华加成空间力量获得量',
    'Reduces the requirements of the first three challenges.': '降低前三个挑战的需求',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //谚语
    'ALTERNATE PROGRESSION': '交替级数',
    'THATS NOT VERY CREATIVE': '那不是很创意',
    'COOL AND NEW PRESTIGE TREE': '酷和新的声望树',
    'COOL AND NEW INCREMENTAL GAME': '很酷的新增量游戏',
    'CLASS POINTS CUBED': '阶级点的立方',
    'CLASS POINTS INFINITED CUBED': '阶级点无限的立方',
    'CLASS POINTS CUBED SQUARED': '阶级点的立方的平方',
    'CLASS POINTS INFINITED HEXERACTED': '阶级点无限六边形',
    'CLASS POINTS INFINITED PENTERACTED': '阶级点无穷五元数',
    'CLASS POINTS SQUARED': '阶级点平方',
    'CLASS POINTS INFINITED TESSERACTED': '阶级点无限细分',
    'CLASS POINTS SQUARED SQUARED': '阶级点平方的平方',
    'CLASS POINTS TESSERACTED': '阶级点细分',
    'CLASS POINTS TESSERACTED SQUARED': '阶级点细分的平方',
    'FULLY REFURBISHED': '全面翻新',
    'FASTER LEVEL UPS': '更快级别的UPS',
    'CARAPACIPHONY': '卡拉帕尼',
    'CLASSPHONY': '上流社会',
    'PROGRESSION CUBED': '进阶的立方',
    'PROGRESSION SQUARED': '进阶的平方',
    'IT CAN NOT BE UNDONE': '无法撤消',
    'IT IS TOO LATE TO DO ANYTHING ELSE': '一切都太迟了',
    'IT MUST HAPPENS': '它必须发生',
    'JUST A LITTLE BIT MORE': '只是多了一点点',
    'THE ASCENSION IS ALMOST HERE': '几乎到了这里',
    'EVERYTHING IS ACTIVE': '全部激活了',
    'EVERYTHING IS ALMOST READY': '一切都准备好了',
    'REPLACING ALL THE PROCESS': '替换所有的进度',
    'FULLY POWERED': '电已充满',
    'AGE OF GROWTH': '成长时代',
    'SIGNPHONY': '招牌',
    'SPECIAL TREATMENT': '特别待遇',
    'SWAYPHONY': '斯旺·霍尼',
    'THE HEMO ERA': '血统时代',
    'ALMOST THE ENTIRE UPGRADE PANEL': '基本上是所有的升级面板',
    'WAIT THIS ISNT HOMESTUCK': '等等这不是HOMESTUCK',
    'REMOVE CARPAL TUNNEL': '移除腕管',
    'IS THIS THING A JOKE': '你在开玩笑吗',
    'REMOVE CARPAL TUNNEL AGAIN': '再次移除腕管',
    'ADD SOMETHING TO THE GAME': '在游戏里添加些东西',
    'REMOVE MORE CARPAL TUNNEL': '移除更多腕管',
    'NO I MEAN THE HOMESTUCK SOMETHING': '现在我稍微理解HOMESTUCK',
    'TIME IS FASTER BASED ON SPACE': '空间会使时间加速',
    'TIME IS BOOSTING SPACE': '时间会加成空间',
    'RECONSTRUCT STRATEGY': '重新调整策略',
    'INCREASE BOOSTING EFFICIENCY': '增强增强器效果',
    'ALSO RECONSTRUCT STRATEGY': '再次调整策略',
    'A REPLACEMENT UPGRADE': '一个升级的替代品',
    'AUTOMATE SPACE GENERATORS': '自动空间发生器',
    'FINALLY UPGRADES AUTOBUYERS': '最后的升级自动化',
    'TIME AUTO BOOSTER SQUARED': '时间自动购买者被平方了',
    'USE THE TIME POWER': '掌握时间力量',
    'POWER THE TIME': '赋予时间力量',
    'DILATE THE TIME CONTINUUM': '增强时间连续性',
    'SPACE IS BOOSTING TIME': '空间增强时间',
    'THIS IS BORING': '这玩意真无聊',
    'MIND IS BOOSTING TIME': '精神增强时间',
    'HEART IS BOOSTING TIME': '心灵增强时间',
    'NOW WITH MORE IDLE': '现在需要更多的放置',
    'WORRY ABOUT UPGRADES LESS': '为升级不够多而发愁',
    'SUSPICIOUSLY SIMILAR MILESTONE': '一个可疑的相似的里程碑',
    'WORRY LESS ABOUT UPGRADES AGAIN': '再次为升级不够多而发愁',
    'EXPAND YOUR MIND': '解放你的精神',
    'THE BALNCE IS BROKEN': '打破平衡',
    'MIND BOOSTS POINTS': '精神加成点数',
    'MIND BOOSTS TIME': '精神加成时间',
    'MIND BOOSTS SPACE': '精神加成空间',
    'MIND BOOSTS SPACE AGAIN': '精神再次加成空间',
    'THESE ARE GIVING ME EPILEPSY': '这些东西令我疯狂',
    'POINT BOOSTERS': '点数增强者',
    'RESET PROOFING': '重新校对',
    'POINTS BOOST HEART': '点数加成心灵',
    'TIME BOOSTS HEART': '时间加成心灵',
    'SPACE BOOSTS HEART': '空间加成心灵',
    'SPACE BOOSTS HEART AGAIN': '空间再次加成心灵',
    'BETTER SCALING': '更好的购买方式',
    'EVEN LESS JITTERING': '不必再操心了',
    'BOOSTING PRODUCTION': '加成生产器',
    'A QUALITY OF LIFE MILESTONE': '提高生活质量的里程碑',
    'WHY ISNT THIS FIRST': '为什么这个不是第一个',
    'OPEN THEE HEART': '敞开心灵',
    'NO LONGER BALANCED': '再也没有平衡了',
    'PLAYER': '玩家',
    'IF YOU CAN': '如果你可以',
    'SEE THIS': '看见这个',
    'THAT MEANS': '那就说明',
    'YOUVE PLAYED ENOUGH': '你已经玩了足够多',
    'TO BE ABLE TO': '从而可以',
    'MAKE DECISIONS': '做出决定',
    'FOR YOURSELF': '为你自己',
    'YOU ARE NOW': '你现在是',
    'A SKILLED PLAYER': '专业玩家',
    'AS SUCH': '如此专业',
    'YOU ARE ENTITLED': '你有权利',
    'TO WHAT HAPPENS': '了解一下',
    'DURING YOUR JOURNEY': '发生了什么',
    'I AM SO': '我非常',
    'SO PROUD': '非常骄傲',
    'OF YOU': '为你骄傲',
    'HOPES AND DREAMS': '梦与希望',
    'UPGRADES AND JUSTICE': '升级与正义',
    'UNEXPECTED SYNERGY': '意料之外的配合',
    'RAGEFUL HOPE': '满溢愤怒的希望',
    'BRINGER OF CHAOS': '混沌使者',
    'COMMENCE DESTRUCTION': '毁灭开始',
    'HOPEFUL RAGE': '充满希望的愤怒',
    'GET TO THE POINT': '切入“重点”',
    'TIME DILATION': '时间膨胀',
    'SPACE EXPANSION': '空间扩张',
    'TETRATION PROBLEM': '迭代运算问题',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //原样
//    'Act': '相位',
//    'A': '相',
//    'C': '阶',
//    'P': '赞',
//    'D': '德',
    '×e': '×e',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Hope Power boosts Time Power gain": "心灵力量加成时间力量获得量",
    "Hope Power boosts Space Power gain": "心灵力量加成空间力量获得量",
    "Hope Power boosts point gain": "心灵力量加成点数获得量",
    "Hope Power": "心灵力量",
    "Space Generators act as if they're bought 10× when you only buy once. Buying this does a forced Heart reset.": "空间发生器一次性购买十个，购买这个会强制进行一次心灵重置",
    "Space Generator": "空间发生器",
    "Time Boosters scale less and worth more.": "时间增强器涨价更慢且效果更强。",
    "Time Boosters": "时间增强器",
    "Time Multiplier": "时间加倍器",
    "Time Played: ": "游戏时长：",
    "based on Homestuck by Andrew Hussie (of course)": "基于Andrew Hussie的Homestuck（当然）",
    "Offline Prod: ": "离线产出: ",
    "Theme: ": "主题: ",
    "Autosave: ": "自动保存: ",
    "Completed Challenges: ": "完成的挑战：",
    "High-Quality Tree: ": "高质量树：",
    "Show Milestones: ": "显示里程碑：",
    "which are raising the cost of ": "这增加了成本关于",
    "which are raising the effect of ": "这正在提高效果关于",
    "Life ": "生命",
    "Blood ": "血液",
    "Breath ": "呼吸",
    "Doom ": "厄运",
    "Heart: ": "心灵",
    "Hope: ": "希望",
    "Life: ": "生命",
    "Mind: ": "精神",
    "Rage: ": "愤怒",
    "Space: ": "空间",
    "Time: ": "时间",
    "Blood: ": "血液",
    "Breath: ": "呼吸",
    "Light: ": "光明",
    "Void: ": "虚空",
    "Doom: ": "厄运",
    "Cost: ": "成本: ",
    "Slyph Power": "空气精灵力量",
    "Seer Power": "先知力量",
    "Lord Power": "上帝力量",
    "Muse Power": "缪斯力量",
    "Prince Power": "王子力量",
    "Page Power": "页面力量",
    "Maid Power": "女佣力量",
    "Mage Power": "魔法力量",
    "Knight Power": "骑士力量",
    "All of your Class Powers are giving you ": "您所有的阶级力量都给您 ",
    "Bard Power": "吟游力量",
    "Req: ": "需要: ",
    "which are giving a ": "这给了 ",
    "You gain Class Points faster based on your ": "你获得阶级点数更快，基于你的",
    "Boosts all of the second upgrade row effect, based on ": "提升所有的第二升级行效果，基于",
    "Replace the process of getting Aspect ": "替换得到相位的过程",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "9.869e598/s).": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Time Power\n			": "时间力量",
    "Space\n			": "空间",
    "Space power": "空间力量",
    "If you can see this message, that means the game has detected inconsistent version number between files.": "如果您看到此消息，则表明游戏检测到文件之间的版本号不一致。",
    "Please try again later, or if this screen has been up for more than 30 minutes, please contact the mod author.": "请稍后再试，或者如果该屏幕显示超过30分钟，请与mod作者联系。",
    "This can be caused by the website currently being updated and not ready yet or there is an error causing the files to be read incorrectly.": "这可能是由于当前正在更新的网站尚未准备就绪引起的，或者是由于错误导致文件读取不正确。",
    "If you can see this something bad must've happened!": "如果您看到此错误，则必定发生了坏事！",
    "Massive Slowdown": "大规模减速",
    " no longer takes your Aspect Points away.": "不再带走您的相位点。",
    " Dersites": " Dersites",
    " Prospitians": " Prospitians",
    " Class Points per second.": " 阶级点每秒。",
    " Blue Symphony": "蓝色交响曲",
    " Bronze Symphony": "青铜色交响曲",
    " Fuchsia Symphony": "紫红色交响曲",
    " Gold Symphony": "金色交响曲",
    " Indigo Symphony": "靛蓝色交响曲",
    " Jade Symphony": "玉色交响曲",
    " Lime Symphony": "石灰色交响曲",
    " Olive Symphony": "橄榄色交响曲",
    " Purple Symphony": "紫色交响曲",
    " Rust Symphony": "锈色交响曲",
    " Teal Symphony": "蓝绿色交响曲",
    " Violet Symphony": "紫罗兰色交响曲",
    " boost to point gain.": "提升到点的收益。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^(.+)直到下一个回切点$/, 
    /^÷(.+),$/, 
    /^(.+)x$/, 
    /^e(.+)\/秒$/, 
    /^(.+)√$/, 
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^(\d+) layers remaining$/, '$1 层剩余'],
    [/^and will need (.+) Echepoints to climb to the next rung.$/, '并且需要$1个回切点才能爬到下一个梯级。'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^which are boosting your Aspect Point gain by ×(.+).\n(.+)Cost: (.+) points$/, '通过以下方式提高您的相位点增益$1。\n成本：$3 点'],
    [/^Power by (.+).\n(.+)Cost: (.+) Aspect Points$/, '力量$1。\n成本：$3 相位点'],
    [/^which is equivalent to climbing (.+) Achievement Rungs on the Echeladder.$/, '这相当于攀登了$1个成就阶梯。'],
    [/^(.+) Breath Essence & (.+) Blood Essence$/, '$1呼吸精华 \＆ $2血液精华'],
    [/^([\d\.,]+)$/, '$1'],
    [/^([\d\.,]+)x$/, '$1x'],
    [/^e([\d\.,]+)$/, 'e$1'],
    [/^ee([\d\.,]+)$/, 'ee$1'],
    [/^Next at (.+) points$/, '下一个在 $1 点'],
    [/^Goal: (.+)e(.+) points$/, '目标： $1e$2 点'],
    [/^\÷e(.+)e(.+) and \÷e(.+)e(.+), respectively.$/, '分别÷e$1e$2 和 ÷e$3e$4'],
    [/^\÷ee(.+) and \÷ee(.+), respectively.$/, '分别÷ee$1 和 ÷ee$2'],
    [/^(.+) Mind Power\n			$/, '$1 精神力量'],
    [/^(.+) Hope Power\n			$/, '$1 希望力量'],
    [/^(.+) Mind Power\n			$/, '$1 精神力量'],
    [/^Point gain is softcapped beyond (.+)e(.+) points, with a magnitude of (.+).$/, '点数获取将在$1e$2到达软上限，影响级别为$3'],
    [/^Raises Time Power gain to the power of \^(.+)$/, '时间力量获得量变为^$1'],
    [/^Raises Space Power gain to the power of \^(.+)$/, '空间力量获得量变为^$1'],
    [/^Tetrates point gain by \^\^(.+)$/, '点数获得量变为^^$1'],
    [/^(.+) \/ (.+) completions$/, '$1 / $2 完成次数'],
    [/^Hope Power \(+e(.+)e(.+)\/s\).$/, '心灵力量 (+e$1e$2/s)'],
    [/^×e(.+),$/, '×e$1,'],
    [/^(.+) OOMs\/秒$/, '$1 OOMs/秒'],
    [/^(.+)Hope Essence$/, '$1心灵精华'],
    [/^(.+)Rage Essence$/, '$1愤怒精华'],
    [/^(.+)Mind Power$/, '$1精神力量'],
    [/^(.+)Heart Power$/, '$1心灵力量'],
    [/^(.+)Space Power$/, '$1空间力量'],
    [/^Current endgame: (.+) points$/, '当前的残局：$1点'],
    [/^(.+) \/ (.+) Class Points(.+)\n(.+)$/, '$1 \/ $2 阶级点'],
    [/^You are getting (.+) Aspect Points per second.$/, '您每秒获得$1相位点。'],
    [/^Cost: (.+) points\n(.+)$/, '成本: $1 点'],
    [/^(.+)Try reloading the page, and if it don't help, contact the mod author!\n(.+)$/, '尝试重新加载页面，如果没有帮助，请联系mod作者!'],
    [/^You have (.+)Space, which are giving a (.+) boost to Time Power gain$/, '你有$1空间，将每秒生产$2空间力量'],
    [/^which are giving (.+)Space per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generators per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generator\^2s per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器^2每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generator\^3s per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器^3每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generator\^4s per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器^4每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generator\^5s per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器^5每秒。\n$2成本：$3 空间力量'],
    [/^which are making all Space Generators (.+)faster.\n(.+)Cost: (.+) Space$/, '将使所有发生器$1倍加速。\n$2成本：$3 空间'],
    [/^which are making all Time Multipliers (.+) cheaper.\n(.+)Req: (.+) Time Power$/, '将使全部时间加倍器便宜$1倍。\n$2成本：$3 时间力量'],
    [/^which are making all Time Multipliers and Time Boosters (.+) cheaper.\n(.+)Req: (.+) Time Boosters$/, '将使你全部时间加倍器和时间增强器便宜$1倍。\n$2成本：$3 时间增强器'],
    [/^which are boosting your point gain by (.+).\n(.+)Cost: (.+) Time Power$/, '将使你的点数获取乘以$1倍。\n$2成本：$3 时间力量'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);