/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Aspects': '相位',
    'Aspect Points': '相位点',
//    'Prospit': '赞成',
//    'Derse': '德赛',
    'Class': '课程',
    'Class Points': '课程点',
    'Loading...': '加载中...',
    'Play Again': '重玩',
    'points': '点数',
    'Genesis -': '创世记-',
    'Keep Going': '继续',
    'Offline Time': '离线时间',
    'Multipliers': '倍数',
    'Time Power': '时间力量',
    'Currently': '当前',
    "Time Multipliers": "时间加倍器",
    'Absorb +': '重置 +',
    'Space Power': '空间力量',
    'Next at': '下一个需要',
    'The Modding Tree\n							Discord': 'The Modding Tree\n							Discord',
    'Milestones': '里程碑',
    'BLESSING OF LIFE': '生命的祝福',
    'Upgrades': '升级',
    'Mind Power': '精神力量',
    'Heart Power': '心灵力量',
    "Space Generator": "空间发生器",
    "Space Generator\^2": "空间发生器^2",
    "Space Generator\^3": "空间发生器^3",
    "Space Generator\^4": "空间发生器^4",
    "Space Generator\^5": "空间发生器^5",
    'Hope Essence': '希望精华',
    'Hope Power': '希望力量',
    'Challenges': '挑战',
    'Completed': '已完成',
    'Exit Early': '提前退出',
    'Finish': '完成',
    'Enhancements': '增幅',
    'Researches': '研究',
    'Light Power': '光明力量',
    'Point Levels': '点数等级',
    'Time Levels': '时间等级',
    'Space Levels': '空间等级',
    'Mind Levels': '精神等级',
    'Heart Levels': '心灵等级',
    'Hope Levels': '希望等级',
    'Rage Levels': '愤怒等级',
    'Rage Essence': '愤怒精华',
    'Blessing': '祝福',
    'Wraths': '盛怒',
    'Synergism': '协同',
    'Breath Essence': '呼吸精华',
    'Blood Essence': '鲜血精华',
    'Blood Power.': '鲜血力量',
    'Blood Power.': '呼吸力量',
    'Time Multiplier': '时间加倍器',
    'Time Multiplier\^': '时间加倍器^',
    'Time Multiplier\^\∞ Synergizer': '时间加倍器^∞协同器',
    'Time Booster Synergizer': '时间增强器协同器',
    'Time Booster\^2 Synergizer': '时间增强器^2协同器',
    "Space Generator": "空间发生器",
    "Space Generator\^": "空间发生器^",
    'Space Generator\^\∞ Synergizer': '空间发生器^∞协同器',
    'Space Synergizer': '空间协同器',
    'Space Accelerator Synergizer': '空间加速器协同器',
    'Heart Synergizer': '心灵协同器',
    'Heart Upgrade Synergizer': '心灵升级协同器',
    'Heart Upgrade\^2 Synergizer': '心灵升级^2协同器',
    'Rage Challenge Synergizer': '愤怒挑战协同器',
    'Rage Challenge\^2 Synergizer': '愤怒挑战^2协同器',
    'Rage Challenge\^3 Synergizer': '愤怒挑战^3协同器',
    'Void Synergizer': '虚空协同器',
    'Void Enhancement Synergizer': '虚空增幅协同器',
    'Doom Synergizer': '灾厄协同器',
    'Doom Effect Synergizer': '灾厄效果协同器',
    'Blood Synergizer': '鲜血协同器',
    'Blood Synergizer\^': '鲜血协同器^',
    'Doom Power': '灾厄力量',
    'Life Power': '生命力量',
    'Mind Synergizer': '精神协同器',
    'Mind Upgrade Synergizer': '精神升级协同器',
    'Mind Upgrade\^2 Synergizer': '精神升级^2协同器',
    'Hope Upgrade Synergizer': '希望升级协同器',
    'Hope Upgrade\^6 Synergizer': '希望升级^6协同器',
    'Hope Upgrade\^3 Synergizer': '希望升级^3协同器',
    'Light Discoveries\^\∞ Synergizer': '光明研究^∞协同器',
    'Light Synergizer': '光明协同器',
    'Life Synergizer': '生命协同器',
    'Life Effect Synergizer': '生命效果协同器',
    'Breath Synergizer\^': '呼吸协同器^',
    'Breath Synergizer': '呼吸协同器',
    'Breath Power.': '呼吸力量',
    'Act': '时代',
    'Echetasks': '阶层任务',
    'Time Shards': '时间碎片',
    'Time Essence': '时间精华',
    'Mind Shards': '精神碎片',
    'Mind Essence': '精神精华',
    'Space Shards': '空间碎片',
    'Space Essence': '空间精华',
    'Heart Shards': '心灵碎片',
    'Heart Essence': '心灵精华',
    'Hope Shards': '希望碎片',
    'Rage Power': '愤怒力量',
    'Rage Shards': '愤怒碎片',
    'Light Shards': '光明碎片',
    'Light Essence': '光明精华',
    'Void Power': '虚空力量',
    'Void Shards': '虚空碎片',
    'Void Essence': '虚空精华',
    'Life Shards': '生命碎片',
    'Life Essence': '生命精华',
    'Doom Shards': '灾厄碎片',
    'Doom Essence': '灾厄精华',
    'Breath Power': '呼吸力量',
    'Breath Shards': '呼吸碎片',
    'Blood Power': '鲜血力量',
    'Blood Shards': '鲜血碎片',
    'Automatically get Time Power.': '自动购买时间力量',
    'Automatically get Space Power.': '自动购买空间力量',
    'Automatically get Mind Power.': '自动购买精神力量',
    'Automatically get Rage Power.': '自动购买愤怒力量',
    'Automatically get Heart Power.': '自动购买心灵力量',
    'Automatically get Hope Power.': '自动购买希望力量',
    'Automatically get Life Power.': '自动购买生命力量',
    'Automatically get Light Power.': '自动购买光明力量',
    'Automatically get Void Power.': '自动购买虚空力量',
    'Automatically get Doom Power.': '自动购买灾厄力量',
    'Automatically get Breath Power.': '自动购买呼吸力量',
    'Automatically get Blood Power.': '自动购买鲜血力量',
    'Automatically get Time Shards.': '自动购买时间碎片',
    'Automatically get Space Shards.': '自动购买空间碎片',
    'Automatically get Heart Shards.': '自动购买心灵碎片',
    'Automatically get Mind Shards.': '自动购买精神碎片',
    'Automatically get Hope Shards.': '自动购买希望碎片',
    'Automatically get Rage Shards.': '自动购买愤怒碎片',
    'Automatically get Light Shards.': '自动购买光明碎片',
    'Automatically get Void Shards.': '自动购买虚空碎片',
    'Automatically get Doom Shards.': '自动购买灾厄碎片',
    'Automatically get Life Shards.': '自动购买生命碎片',
    'Automatically get Breath Shards.': '自动购买呼吸碎片',
    'Automatically get Blood Shards.': '自动购买鲜血碎片',
    'Automatically get Time Essence.': '自动购买时间精华',
    'Automatically get Space Essence.': '自动购买空间精华',
    'Automatically get Heart Essence.': '自动购买心灵精华',
    'Automatically get Mind Essence.': '自动购买精神精华',
    'Automatically get Hope Essence.': '自动购买希望精华',
    'Automatically get Rage Essence.': '自动购买愤怒精华',
    'Automatically get Light Essence.': '自动购买光明精华',
    'Automatically get Void Essence.': '自动购买虚空精华',
    'Automatically get Doom Essence.': '自动购买灾厄精华',
    'Automatically get Life Essence.': '自动购买生命精华',
    'Automatically get Breath Essence.': '自动购买呼吸精华',
    'Automatically get Blood Essence.': '自动购买鲜血精华',
    'Getting Time Shards no longer takes your Aspect Points away.': '购买时间碎片不再消耗相位点',
    'Getting Space Shards no longer takes your Aspect Points away.': '购买空间碎片不再消耗相位点',
    'Getting Hope Shards no longer takes your Aspect Points away.': '购买希望碎片不再消耗相位点',
    'Getting Rage Shards no longer takes your Aspect Points away.': '购买愤怒碎片不再消耗相位点',
    'Getting Heart Shards no longer takes your Aspect Points away.': '购买心灵碎片不再消耗相位点',
    'Getting Mind Shards no longer takes your Aspect Points away.': '购买精神碎片不再消耗相位点',
    'Getting Life Shards no longer takes your Aspect Points away.': '购买生命碎片不再消耗相位点',
    'Getting Light Shards no longer takes your Aspect Points away.': '购买光明碎片不再消耗相位点',
    'Getting Doom Shards no longer takes your Aspect Points away.': '购买灾厄碎片不再消耗相位点',
    'Getting Void Shards no longer takes your Aspect Points away.': '购买虚空碎片不再消耗相位点',
    'Getting Breath Shards no longer takes your Aspect Points away.': '购买呼吸碎片不再消耗相位点',
    'Getting Blood Shards no longer takes your Aspect Points away.': '购买鲜血碎片不再消耗相位点',
    'Getting Time Essence no longer takes your Aspect Points away.': '购买时间精华不再消耗相位点',
    'Getting Space Essence no longer takes your Aspect Points away.': '购买空间精华不再消耗相位点',
    'Getting Mind Essence no longer takes your Aspect Points away.': '购买精神精华不再消耗相位点',
    'Getting Heart Essence no longer takes your Aspect Points away.': '购买心灵精华不再消耗相位点',
    'Getting Hope Essence no longer takes your Aspect Points away.': '购买希望精华不再消耗相位点',
    'Getting Rage Essence no longer takes your Aspect Points away.': '购买愤怒精华不再消耗相位点',
    'Getting Light Essence no longer takes your Aspect Points away.': '购买光明精华不再消耗相位点',
    'Getting Void Essence no longer takes your Aspect Points away.': '购买虚空精华不再消耗相位点',
    'Getting Life Essence no longer takes your Aspect Points away.': '购买生命精华不再消耗相位点',
    'Getting Doom Essence no longer takes your Aspect Points away.': '购买灾厄精华不再消耗相位点',
    'Getting Breath Essence no longer takes your Aspect Points away.': '购买呼吸精华不再消耗相位点',
    'Getting Blood Essence no longer takes your Aspect Points away.': '购买鲜血精华不再消耗相位点',
    'Passive': '被动',
    'Rogue Power': '游侠力量',
    'Heir Power': '继承人力量',
    'Knight Power': '骑士力量',
    'Lord Power': '上帝力量',
    'Mage Power': '法师力量',
    'Witch Power': '巫师力量',
    'Page Power': '历史力量',
    'Thief Power': '盗贼力量',
    'Maid Power': '女仆力量',
    'Slyph Power': '希尔芙力量',
    'Bard Power': '诗人力量',
    'Seer Power': '先知力量',
    'Prince Power': '王子力量',
    'Muse Power': '缪斯力量',
    'Compact Mode': '缩略图模式',
    'on': '开启',
    'off': '关闭',
    'which are giving a': '可以提供',
    'Aries': '阿尔斯',
    'Arga': '阿尔加',
    'Arza': '阿尔扎',
    'Aro': '阿尔罗',
    'Arrius': '阿尔乌丝',
    'Ariborn': '阿尔伯恩',
    'Arpia': '阿尔匹亚',
    'Arittarius': '阿尔塔乌斯',
    'Arsces': '阿尔瑟斯',
    'Armini': '阿尔米尼',
    'Arun': '阿尔伦',
    'Arcen': '阿尔坎',
    'Tauries': '塔尔斯',
    'Taurga': '塔尔加',
    'Taurza': '塔尔扎',
    'Tauro': '塔尔罗',
    'Taurrius': '塔尔乌丝',
    'Tauriborn': '塔尔伯恩',
    'Taurpia': '塔尔匹亚',
    'Taurittarius': '塔尔塔乌斯',
    'Taursces': '塔尔瑟斯',
    'Taurmini': '塔尔米尼',
    'Taurun': '塔尔伦',
    'Taurcen': '塔尔坎',
    'Gemries': '吉米斯',
    'Gemga': '吉米加',
    'Gemza': '吉米扎',
    'Gemo': '吉米罗',
    'Gemrius': '吉米乌丝',
    'Gemiborn': '吉米伯恩',
    'Gempia': '吉米匹亚',
    'Gemittarius': '吉米塔乌斯',
    'Gemsces': '吉米瑟斯',
    'Gemini': '吉米尼',
    'Gemun': '吉米伦',
    'Gemcen': '吉米坎',
    'Canries': '坎瑞斯',
    'Canga': '坎加',
    'Canza': '坎扎',
    'Cano': '坎罗',
    'Canrius': '坎瑞乌丝',
    'Caniborn': '坎尼伯恩',
    'Canpia': '坎匹亚',
    'Canittarius': '坎尼塔乌斯',
    'Cansces': '坎瑟斯',
    'Camini': '坎米尼',
    'Canun': '坎伦',
    'Cancen': '坎坎',
    'Leries': '雷瑞斯',
    'Lega': '雷加',
    'Leza': '雷扎',
    'Leo': '雷罗',
    'Lerius': '雷瑞乌丝',
    'Leiborn': '雷伯恩',
    'Lepia': '雷匹亚',
    'Leittarius': '雷塔乌斯',
    'Lesces': '雷瑟斯',
    'Lemini': '雷米尼',
    'Leun': '雷伦',
    'Lecen': '雷坎',
    'Viries': '瓦尔瑞斯',
    'Virga': '瓦尔加',
    'Virza': '瓦尔扎',
    'Viro': '瓦尔罗',
    'Virrius': '瓦尔乌丝',
    'Viriborn': '瓦尔伯恩',
    'Virpia': '瓦尔匹亚',
    'Virittarius': '瓦尔塔乌斯',
    'Virsces': '瓦尔瑟斯',
    'Virmini': '瓦尔米尼',
    'Virun': '瓦尔伦',
    'Vircen': '瓦尔坎',
    'Libries': '李伯瑞斯',
    'Liga': '李加',
    'Libza': '李扎',
    'Libo': '李罗',
    'Lirius': '李乌丝',
    'Liiborn': '李伯恩',
    'Lipia': '李匹亚',
    'Libittarius': '李塔乌斯',
    'Libsces': '李瑟斯',
    'Limini': '李米尼',
    'Libun': '李伦',
    'Licen': '李坎',
    'Scories': '斯库瑞斯',
    'Scorga': '斯库加',
    'Scorza': '斯库扎',
    'Scoro': '斯库罗',
    'Scorrius': '斯库乌丝',
    'Scoriborn': '斯库伯恩',
    'Scorpia': '斯库匹亚',
    'Scorittarius': '斯库塔乌斯',
    'Scorsces': '斯库瑟斯',
    'Scormini': '斯库米尼',
    'Scorun': '斯库伦',
    'Scorcen': '斯库坎',
    'Sagiries': '沙基瑞斯',
    'Sagiga': '沙基加',
    'Sagiza': '沙基扎',
    'Sagio': '沙基罗',
    'Sagirius': '沙基乌丝',
    'Sagiiborn': '沙基伯恩',
    'Sagipia': '沙基匹亚',
    'Sagiittarius': '沙基塔乌斯',
    'Sagisces': '沙基瑟斯',
    'Sagimini': '沙基米尼',
    'Sagiun': '沙基伦',
    'Sagicen': '沙基坎',
    'Capries': '卡普瑞斯',
    'Capriga': '卡普加',
    'Capriza': '卡普扎',
    'Caprio': '卡普罗',
    'Capririus': '卡普乌丝',
    'Capriborn': '卡普伯恩',
    'Capripia': '卡普匹亚',
    'Caprittarius': '卡普塔乌斯',
    'Caprisces': '卡普瑟斯',
    'Caprimini': '卡普米尼',
    'Capriun': '卡普伦',
    'Capricen': '卡普坎',
    'Aquaries': '阿库瑞斯',
    'Aquaga': '阿库加',
    'Aquaza': '阿库扎',
    'Aquao': '阿库罗',
    'Aquarius': '阿库乌丝',
    'Aquaiborn': '阿库伯恩',
    'Aquapia': '阿库匹亚',
    'Aquaittarius': '阿库塔乌斯',
    'Aquasces': '阿库瑟斯',
    'Aquamini': '阿库米尼',
    'Aquiun': '阿库伦',
    'Aquacen': '阿库坎',
    'Aries gain.': '阿尔斯获得量',
    'Arga gain.': '阿尔加获得量',
    'Arza gain.': '阿尔扎获得量',
    'Aro gain.': '阿尔罗获得量',
    'Arrius gain.': '阿尔乌丝获得量',
    'Ariborn gain.': '阿尔伯恩获得量',
    'Arpia gain.': '阿尔匹亚获得量',
    'Arittarius gain.': '阿尔塔乌斯获得量',
    'Arsces gain.': '阿尔瑟斯获得量',
    'Armini gain.': '阿尔米尼获得量',
    'Arun gain.': '阿尔伦获得量',
    'Arcen gain.': '阿尔坎获得量',
    'Tauries gain.': '塔尔斯获得量',
    'Taurga gain.': '塔尔加获得量',
    'Taurza gain.': '塔尔扎获得量',
    'Tauro gain.': '塔尔罗获得量',
    'Taurrius gain.': '塔尔乌丝获得量',
    'Tauriborn gain.': '塔尔伯恩获得量',
    'Taurpia gain.': '塔尔匹亚获得量',
    'Taurittarius gain.': '塔尔塔乌斯获得量',
    'Taursces gain.': '塔尔瑟斯获得量',
    'Taurmini gain.': '塔尔米尼获得量',
    'Taurun gain.': '塔尔伦获得量',
    'Taurcen gain.': '塔尔坎获得量',
    'Gemries gain.': '吉米斯获得量',
    'Gemga gain.': '吉米加获得量',
    'Gemza gain.': '吉米扎获得量',
    'Gemo gain.': '吉米罗获得量',
    'Gemrius gain.': '吉米乌丝获得量',
    'Gemiborn gain.': '吉米伯恩获得量',
    'Gempia.': '吉米匹亚获得量',
    'Gemittarius gain.': '吉米塔乌斯获得量',
    'Gemsces gain.': '吉米瑟斯获得量',
    'Gemini gain.': '吉米尼获得量',
    'Gemun gain.': '吉米伦获得量',
    'Gemcen gain.': '吉米坎获得量',
    'Canries gain.': '坎瑞斯获得量',
    'Canga gain.': '坎加获得量',
    'Canza gain.': '坎扎获得量',
    'Cano gain.': '坎罗获得量',
    'Canrius gain.': '坎瑞乌丝获得量',
    'Caniborn gain.': '坎尼伯恩获得量',
    'Canpia gain.': '坎匹亚获得量',
    'Canittarius gain.': '坎尼塔乌斯获得量',
    'Cansces gain.': '坎瑟斯获得量',
    'Camini gain.': '坎米尼获得量',
    'Canun gain.': '坎伦获得量',
    'Cancen gain.': '坎坎获得量',
    'Leries gain.': '雷瑞斯获得量',
    'Lega gain.': '雷加获得量',
    'Leza gain.': '雷扎获得量',
    'Leo gain.': '雷罗获得量',
    'Lerius gain.': '雷瑞乌丝获得量',
    'Leiborn gain.': '雷伯恩获得量',
    'Lepia gain.': '雷匹亚获得量',
    'Leittarius gain.': '雷塔乌斯获得量',
    'Lesces gain.': '雷瑟斯获得量',
    'Lemini gain.': '雷米尼获得量',
    'Leun gain.': '雷伦获得量',
    'Lecen gain.': '雷坎获得量',
    'Viries gain.': '瓦尔瑞斯获得量',
    'Virga gain.': '瓦尔加获得量',
    'Virza gain.': '瓦尔扎获得量',
    'Viro gain.': '瓦尔罗获得量',
    'Virrius gain.': '瓦尔乌丝获得量',
    'Viriborn gain.': '瓦尔伯恩获得量',
    'Virpia gain.': '瓦尔匹亚获得量',
    'Virittarius gain.': '瓦尔塔乌斯获得量',
    'Virsces gain.': '瓦尔瑟斯获得量',
    'Virmini gain.': '瓦尔米尼获得量',
    'Virun gain.': '瓦尔伦获得量',
    'Vircen gain.': '瓦尔坎获得量',
    'Libries gain.': '李伯瑞斯获得量',
    'Liga gain.': '李加获得量',
    'Libza gain.': '李扎获得量',
    'Libo gain.': '李罗获得量',
    'Lirius gain.': '李乌丝获得量',
    'Liiborn gain.': '李伯恩获得量',
    'Lipia gain.': '李匹亚获得量',
    'Libittarius gain.': '李塔乌斯获得量',
    'Libsces gain.': '李瑟斯获得量',
    'Limini gain.': '李米尼获得量',
    'Libun gain.': '李伦获得量',
    'Licen gain.': '李坎获得量',
    'Scories gain.': '斯库瑞斯获得量',
    'Scorga gain.': '斯库加获得量',
    'Scorza gain.': '斯库扎获得量',
    'Scoro gain.': '斯库罗获得量',
    'Scorrius gain.': '斯库乌丝获得量',
    'Scoriborn gain.': '斯库伯恩获得量',
    'Scorpia gain.': '斯库匹亚获得量',
    'Scorittarius gain.': '斯库塔乌斯获得量',
    'Scorsces gain.': '斯库瑟斯获得量',
    'Scormini gain.': '斯库米尼获得量',
    'Scorun gain.': '斯库伦获得量',
    'Scorcen gain.': '斯库坎获得量',
    'Sagiries gain.': '沙基瑞斯获得量',
    'Sagiga gain.': '沙基加获得量',
    'Sagiza gain.': '沙基扎获得量',
    'Sagio gain.': '沙基罗获得量',
    'Sagirius gain.': '沙基乌丝获得量',
    'Sagiiborn gain.': '沙基伯恩获得量',
    'Sagipia gain.': '沙基匹亚获得量',
    'Sagiittarius gain.': '沙基塔乌斯获得量',
    'Sagisces gain.': '沙基瑟斯获得量',
    'Sagimini gain.': '沙基米尼获得量',
    'Sagiun gain.': '沙基伦获得量',
    'Sagicen gain.': '沙基坎获得量',
    'Capries gain.': '卡普瑞斯获得量',
    'Capriga gain.': '卡普加获得量',
    'Capriza gain.': '卡普扎获得量',
    'Caprio gain.': '卡普罗获得量',
    'Capririus gain.': '卡普乌丝获得量',
    'Capriborn gain.': '卡普伯恩获得量',
    'Capripia gain.': '卡普匹亚获得量',
    'Caprittarius gain.': '卡普塔乌斯获得量',
    'Caprisces gain.': '卡普瑟斯获得量',
    'Caprimini gain.': '卡普米尼获得量',
    'Capriun gain.': '卡普伦获得量',
    'Capricen gain.': '卡普坎获得量',
    'Aquaries gain.': '阿库瑞斯获得量',
    'Aquaga gain.': '阿库加获得量',
    'Aquaza gain.': '阿库扎获得量',
    'Aquao gain.': '阿库罗获得量',
    'Aquarius gain.': '阿库乌丝获得量',
    'Aquaiborn gain.': '阿库伯恩获得量',
    'Aquapia gain.': '阿库匹亚获得量',
    'Aquaittarius gain.': '阿库塔乌斯获得量',
    'Aquasces gain.': '阿库瑟斯获得量',
    'Aquamini gain.': '阿库米尼获得量',
    'Aquiun gain.': '阿库伦获得量',
    'Aquacen gain.': '阿库坎获得量',
    'Piries': '皮瑞斯',
    'Piga': '皮加',
    'Piza': '皮扎',
    'Pio': '皮罗',
    'Pirius': '皮乌丝',
    'Piiborn': '皮伯恩',
    'Pipia': '皮匹亚',
    'Piittarius': '皮塔乌斯',
    'Pisces': '皮瑟斯',
    'Pimini': '皮米尼',
    'Piun': '皮伦',
    'Picen': '皮坎',
    'Derse Points': '神恩点',
    'Dersites': '神恩力量',
    'Dersites.': '神恩力量',
    'boost to': '加成',
    'boost to all': '加成所有',
    'Time Essence.': '时间精华',
    'Space Essence.': '空间精华',
    'Mind Essence.': '精神精华',
    'Heart Essence.': '心灵精华',
    'Hope Essence.': '希望精华',
    'Rage Essence.': '愤怒精华',
    'Light Essence.': '光明精华',
    'Void Essence.': '虚空精华',
    'Doom Essence.': '灾厄精华',
    'Life Essence.': '生命精华',
    'Breath Essence.': '呼吸精华',
    'Blood Essence.': '鲜血精华',
    'Rust sign gains': '锈色符文获取量',
    'Bronze sign gains': '铜色符文获取量',
    'Gold sign gains': '金色符文获取量',
    'Lime sign gains': '石灰色符文获取量',
    'Olive sign gains': '橄榄色符文获取量',
    'Jade sign gains': '玉色符文获取量',
    'Teal sign gains': '蓝绿色符文获取量',
    'Blue sign gains': '蓝色符文获取量',
    'Purple sign gains': '紫色符文获取量',
    'Violet sign gains': '紫罗兰色符文获取量',
    'Fuchsia sign gains': '紫红色符文获取量',
    'Indigo sign gains': '靛蓝色符文获取量',
    'Arist': '阿尔斯特',
    'Argo': '阿尔贡',
    'Arra': '阿尔拉',
    'Arlo': '阿尔洛',
    'Arnius': '阿尔纽斯',
    'Aricorn': '阿尔伊贡',
    'Arpio': '阿尔皮欧',
    'Arittanius': '阿尔坦努斯',
    'Arsci': '阿尔斯西',
    'Armino': '阿尔米诺',
    'Arus': '阿尔乌',
    'Arcer': '阿尔瑟',
    'Taurist': '塔尔斯特',
    'Taurgo': '塔尔贡',
    'Taurra': '塔尔拉',
    'Taurlo': '塔尔洛',
    'Taurnius': '塔尔纽斯',
    'Tauricorn': '塔尔伊贡',
    'Taurpio': '塔尔皮欧',
    'Taurittanius': '塔尔坦努斯',
    'Taursci': '塔尔斯西',
    'Taurmino': '塔尔米诺',
    'Taurus': '塔尔乌',
    'Taurcer': '塔尔瑟',
    'Gemrist': '吉米斯特',
    'Gemgo': '吉米贡',
    'Gemra': '吉米拉',
    'Gemlo': '吉米洛',
    'Gemnius': '吉米纽斯',
    'Gemicorn': '吉米伊贡',
    'Gempio': '吉米皮欧',
    'Gemittanius': '吉米坦努斯',
    'Gemsci': '吉米斯西',
    'Gemino': '吉米米诺',
    'Gemus': '吉米乌',
    'Gemcer': '吉米瑟',
    'Canrist': '坎斯特',
    'Cango': '坎贡',
    'Canra': '坎拉',
    'Canlo': '坎洛',
    'Cannius': '坎纽斯',
    'Canicorn': '坎伊贡',
    'Canpio': '坎皮欧',
    'Canittanius': '坎坦努斯',
    'Cansci': '坎斯西',
    'Camino': '坎米诺',
    'Canus': '坎乌',
    'Cancer': '坎瑟(癌症)',
    'Lerist': '雷斯特',
    'Lego': '雷贡',
    'Lera': '雷拉',
    'Lelo': '雷洛',
    'Lenius': '雷纽斯',
    'Leicorn': '雷伊贡',
    'Lepio': '雷皮欧',
    'Leittanius': '雷坦努斯',
    'Lesci': '雷斯西',
    'Lemino': '雷米诺',
    'Leus': '雷乌',
    'Lecer': '雷瑟',
    'Virist': '瓦尔斯特',
    'Virgo': '瓦尔贡',
    'Virra': '瓦尔拉',
    'Virlo': '瓦尔洛',
    'Virnius': '瓦尔纽斯',
    'Viricorn': '瓦尔伊贡',
    'Virpio': '瓦尔皮欧',
    'Virittanius': '瓦尔坦努斯',
    'Virsci': '瓦尔斯西',
    'Virmino': '瓦尔米诺',
    'Virus': '瓦尔乌',
    'Vircer': '瓦尔瑟',
    'Librist': '李斯特',
    'Ligo': '李贡',
    'Libra': '李拉',
    'Liblo': '李洛',
    'Libnius': '李纽斯',
    'Libicorn': '李伊贡',
    'Lipio': '李皮欧',
    'Libittanius': '李坦努斯',
    'Libsci': '李斯西',
    'Limino': '李米诺',
    'Lius': '李乌',
    'Licer': '李瑟',
    'Scorist': '斯库斯特',
    'Scorgo': '斯库贡',
    'Scorra': '斯库拉',
    'Scorlo': '斯库洛',
    'Scornius': '斯库纽斯',
    'Scoricorn': '斯库伊贡',
    'Scorpio': '斯库皮欧',
    'Scorittanius': '斯库坦努斯',
    'Scorsci': '斯库斯西',
    'Scormino': '斯库米诺',
    'Scorus': '斯库乌',
    'Scorcer': '斯库瑟',
    'Caprist': '卡普斯特',
    'Caprigo': '卡普贡',
    'Caprira': '卡普拉',
    'Caprilo': '卡普洛',
    'Caprinius': '卡普纽斯',
    'Capricorn': '卡普伊贡',
    'Capripio': '卡普皮欧',
    'Caprittanius': '卡普坦努斯',
    'Caprisci': '卡普斯西',
    'Caprimino': '卡普米诺',
    'Caprius': '卡普乌',
    'Capricer': '卡普瑟',
    'Aquarist': '阿库斯特',
    'Aquago': '阿库贡',
    'Aquara': '阿库拉',
    'Aqualo': '阿库洛',
    'Aquanius': '阿库纽斯',
    'Aquicorn': '阿库伊贡',
    'Aquapio': '阿库皮欧',
    'Aquaittanius': '阿库坦努斯',
    'Aquasci': '阿库斯西',
    'Aquamino': '阿库米诺',
    'Aquius': '阿库乌',
    'Aquacer': '阿库瑟',
    'Sagirist': '沙基斯特',
    'Sagigo': '沙基贡',
    'Sagira': '沙基拉',
    'Sagilo': '沙基洛',
    'Saginius': '沙基纽斯',
    'Sagicorn': '沙基伊贡',
    'Sagipio': '沙基皮欧',
    'Sagittanius': '沙基坦努斯',
    'Sagisci': '沙基斯西',
    'Sagimino': '沙基米诺',
    'Sagius': '沙基乌',
    'Sagicer': '沙基瑟',
    'Arist gain.': '阿尔斯特获取量',
    'Argo gain.': '阿尔贡获取量',
    'Arra gain.': '阿尔拉获取量',
    'Arlo gain.': '阿尔洛获取量',
    'Arnius gain.': '阿尔纽斯获取量',
    'Aricorn gain.': '阿尔伊贡获取量',
    'Arpio gain.': '阿尔皮欧获取量',
    'Arittanius gain.': '阿尔坦努斯获取量',
    'Arsci gain.': '阿尔斯西获取量',
    'Armino gain.': '阿尔米诺获取量',
    'Arus gain.': '阿尔乌获取量',
    'Arcer gain.': '阿尔瑟获取量',
    'Taurist gain.': '塔尔斯特获取量',
    'Taurgo gain.': '塔尔贡获取量',
    'Taurra gain.': '塔尔拉获取量',
    'Taurlo gain.': '塔尔洛获取量',
    'Taurnius gain.': '塔尔纽斯获取量',
    'Tauricorn gain.': '塔尔伊贡获取量',
    'Taurpio gain.': '塔尔皮欧获取量',
    'Taurittanius gain.': '塔尔坦努斯获取量',
    'Taursci gain.': '塔尔斯西获取量',
    'Taurmino gain.': '塔尔米诺获取量',
    'Taurus gain.': '塔尔乌获取量',
    'Taurcer gain.': '塔尔瑟获取量',
    'Gemrist gain.': '吉米斯特获取量',
    'Gemgo gain.': '吉米贡获取量',
    'Gemra gain.': '吉米拉获取量',
    'Gemlo gain.': '吉米洛获取量',
    'Gemnius gain.': '吉米纽斯获取量',
    'Gemicorn gain.': '吉米伊贡获取量',
    'Gempio gain.': '吉米皮欧获取量',
    'Gemittanius gain.': '吉米坦努斯获取量',
    'Gemsci gain.': '吉米斯西获取量',
    'Gemino gain.': '吉米米诺获取量',
    'Gemus gain.': '吉米乌获取量',
    'Gemcer gain.': '吉米瑟获取量',
    'Canrist gain.': '坎斯特获取量',
    'Cango gain.': '坎贡获取量',
    'Canra gain.': '坎拉获取量',
    'Canlo gain.': '坎洛获取量',
    'Cannius gain.': '坎纽斯获取量',
    'Canicorn gain.': '坎伊贡获取量',
    'Canpio gain.': '坎皮欧获取量',
    'Canittanius gain.': '坎坦努斯获取量',
    'Cansci gain.': '坎斯西获取量',
    'Camino gain.': '坎米诺获取量',
    'Canus gain.': '坎乌获取量',
    'Cancer gain.': '坎瑟获取量',
    'Lerist gain.': '雷斯特获取量',
    'Lego gain.': '雷贡获取量',
    'Lera gain.': '雷拉获取量',
    'Lelo gain.': '雷洛获取量',
    'Lenius gain.': '雷纽斯获取量',
    'Leicorn gain.': '雷伊贡获取量',
    'Lepio gain.': '雷皮欧获取量',
    'Leittanius gain.': '雷坦努斯获取量',
    'Lesci gain.': '雷斯西获取量',
    'Lemino gain.': '雷米诺获取量',
    'Leus gain.': '雷乌获取量',
    'Lecer gain.': '雷瑟获取量',
    'Virist gain.': '瓦尔斯特获取量',
    'Virgo gain.': '瓦尔贡获取量',
    'Virra gain.': '瓦尔拉获取量',
    'Virlo gain.': '瓦尔洛获取量',
    'Virnius gain.': '瓦尔纽斯获取量',
    'Viricorn gain.': '瓦尔伊贡获取量',
    'Virpio gain.': '瓦尔皮欧获取量',
    'Virittanius gain.': '瓦尔坦努斯获取量',
    'Virsci gain.': '瓦尔斯西获取量',
    'Virmino gain.': '瓦尔米诺获取量',
    'Virus gain.': '瓦尔乌获取量',
    'Vircer gain.': '瓦尔瑟获取量',
    'Librist gain.': '李斯特获取量',
    'Ligo gain.': '李贡获取量',
    'Libra gain.': '李拉获取量',
    'Liblo gain.': '李洛获取量',
    'Libnius gain.': '李纽斯获取量',
    'Libicorn gain.': '李伊贡获取量',
    'Lipio gain.': '李皮欧获取量',
    'Libittanius gain.': '李坦努斯获取量',
    'Libsci gain.': '李斯西获取量',
    'Limino gain.': '李米诺获取量',
    'Lius gain.': '李乌获取量',
    'Licer gain.': '李瑟获取量',
    'Scorist gain.': '斯库斯特获取量',
    'Scorgo gain.': '斯库贡获取量',
    'Scorra gain.': '斯库拉获取量',
    'Scorlo gain.': '斯库洛获取量',
    'Scornius gain.': '斯库纽斯获取量',
    'Scoricorn gain.': '斯库伊贡获取量',
    'Scorpio gain.': '斯库皮欧获取量',
    'Scorittanius gain.': '斯库坦努斯获取量',
    'Scorsci gain.': '斯库斯西获取量',
    'Scormino gain.': '斯库米诺获取量',
    'Scorus gain.': '斯库乌获取量',
    'Scorcer gain.': '斯库瑟获取量',
    'Caprist gain.': '卡普斯特获取量',
    'Caprigo gain.': '卡普贡获取量',
    'Caprira gain.': '卡普拉获取量',
    'Caprilo gain.': '卡普洛获取量',
    'Caprinius gain.': '卡普纽斯获取量',
    'Capricorn gain.': '卡普伊贡获取量',
    'Capripio gain.': '卡普皮欧获取量',
    'Caprittanius gain.': '卡普坦努斯获取量',
    'Caprisci gain.': '卡普斯西获取量',
    'Caprimino gain.': '卡普米诺获取量',
    'Caprius gain.': '卡普乌获取量',
    'Capricer gain.': '卡普瑟获取量',
    'Aquarist gain.': '阿库斯特获取量',
    'Aquago gain.': '阿库贡获取量',
    'Aquara gain.': '阿库拉获取量',
    'Aqualo gain.': '阿库洛获取量',
    'Aquanius gain.': '阿库纽斯获取量',
    'Aquicorn gain.': '阿库伊贡获取量',
    'Aquapio gain.': '阿库皮欧获取量',
    'Aquaittanius gain.': '阿库坦努斯获取量',
    'Aquasci gain.': '阿库斯西获取量',
    'Aquamino gain.': '阿库米诺获取量',
    'Aquius gain.': '阿库乌获取量',
    'Aquacer gain.': '阿库瑟获取量',
    'Sagirist gain.': '沙基斯特获取量',
    'Sagigo gain.': '沙基贡获取量',
    'Sagira gain.': '沙基拉获取量',
    'Sagilo gain.': '沙基洛获取量',
    'Saginius gain.': '沙基纽斯获取量',
    'Sagicorn gain.': '沙基伊贡获取量',
    'Sagipio gain.': '沙基皮欧获取量',
    'Sagittanius gain.': '沙基坦努斯获取量',
    'Sagisci gain.': '沙基斯西获取量',
    'Sagimino gain.': '沙基米诺获取量',
    'Sagius gain.': '沙基乌获取量',
    'Sagicer gain.': '沙基瑟获取量',
    'Pirist': '皮斯特',
    'Pigo': '皮贡',
    'Pira': '皮拉',
    'Pilo': '皮洛',
    'Pinius': '皮纽斯',
    'Picorn': '皮伊贡',
    'Pipio': '皮皮欧',
    'Pittanius': '皮坦努斯',
    'Pisci': '皮斯西',
    'Pimino': '皮米诺',
    'Pius': '皮乌',
    'Picer': '皮瑟',
    'Prospit': '真实',
    'Prospitian': '真实力量',
    'Prospitians': '真实力量',
    'Prospitians.': '真实力量',
    'Prospit Point': '真实点',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Shard and Essence replacements scales better.': '碎片和精华替代品可更好地扩展。',
    'Unlocks special milestones for each of the Lunar Sway (Derse & Prospit) layers.': '解锁月亮支配的(神恩 & proit)层的特殊里程碑。',
    'Unlocks Derse.': '解锁神恩',
    'Unlocks Prospit.': '解锁真实.',
    'Boosts all of the second upgrade row effect, based on Aspect Points, including the above upgrade\'s effect.': '根据相位点增强所有第二个升级行效果，包括上述升级的效果。',
    'Keeps Space Upgrades on Breath and Blood resets.': '在呼吸和鲜血重置时保持空间升级。',
    'Keeps Rage, Hope, Mind and Heart milestones plus Mind and Heart upgrades on Breath and Blood resets.': '保持愤怒，希望，精神和心脏的里程碑，并在重置呼吸和鲜血时保持精神和心脏的升级。',
    'Keeps Light, Void, Life and Doom milestones on Breath and Blood resets.': '在呼吸和鲜血重置时保持光明，虚空，生命和灾厄的里程碑。',
    'Keeps Hope Upgrades and Rage Milestones on Breath and Blood resets.': '在呼吸和鲜血重置上保持希望升级和狂暴里程碑。',
    'Absorbing Breath and Blood Essence no longer resets anything.': '呼吸和鲜血的重置不再重置任何东西。',
    'Automatically do Breath and Blood resets.': '自动执行呼吸和鲜血重置。',
    'Gain the ability to bulk get Time Boosters. Also affects autobuyers.': '获得批量获取时间推进器的能力。 也影响自动购买者。',
    'Keeps Doom Wraths on Breath and Blood resets.': '使末日之怒重置于呼吸和鲜血状态。',
    'Progression': '进阶',
    'Multiplies all of the second upgrade row effect with the fourth root of Skaia level plus 1, after all above power upgrades.': '在以上所有能力升级之后，将所有第二个升级行效果乘以Skaia等级的第四个根再加上1。',
    'You can bulk absorb Breath and Blood ': '你可以批量重置呼吸和鲜血',
    'Prospit is currently having': '真实当前有',
    'Not yet implemented.': '尚未实现。',
    'Signs Viewer': '标志查看器',
    'Derse is currently having': '目前拥有神恩',
    'Currently: ×': '当前: ×',
    'Currently: ÷': '当前: ÷',
    'Currently: \^': '当前: ^',
    'Doubles the Time Shards and Time Essence replacement value.': '将时间碎片和时间精华替换值加倍。',
    'Filling the Echebar gives you 100 levels instead of 1.': '充满阶层进度可以让你升100级而不是1级。',
    'Current effects': '目前的效果',
    'Classes': '阶级',
    'Class Points': '课程点',
    'Abolish your aspect and class progress to get +': '取消您的相位和阶级进度以获取+',
    'All Bronze sign effects boosts all Aspect Point effects.': '所有青铜符号效果提升所有相位点效果。',
    'All Aspect Powers are procedually generated instead of bought.': '所有相位力量都是程序生成的，而不是购买的。',
    'Active': '激活',
    'A NEW AGE': '新时代',
    'Gemcen': '金森',
    'Note: Autobuyers only fire once per second due to performance issues.': '注意：由于性能问题，自动购买者每秒只能触发一次。',
    'Void': '虚空',
    'Light': '光明',
    'Shards': '碎片',
    'Power': '力量',
    'Essence': '精华',
    'Doom': '灾厄',
    'Breath': '呼吸',
    'Blood': '鲜血',
    'Time': '时间',
    'Space': '空间',
    'Rage': '愤怒',
    'Mind': '精神',
    'Life': '生命',
    'Hope': '希望',
    'Heart': '心灵',
    'You currently have': '你当前有',
    'Unlocks Classes': '解锁阶级',
    'Skaia is currently in level': '斯卡亚现在的阶层等级',
    'Meta': '元',
    'Echepoints': '阶层点数',
    'made by ducdat': '由ducdat制作',
    'BUT WHY THOUGH': '但是为什么要思想',
    'T: Absorb Time Power': 'T: 吸取时间的力量',
    'server of the person who made the original game': '最初的游戏制作者的服务器',
    'Homosuck': '绿帽色',
    'Aqua': '水色',
    'NEVER': '从不',
    'INCOMPLETE': '部分',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'ALWAYS': '一直',
    'SHOWN': '显示',
    'ON': '开启',
    'OFF': '关闭',
    'Default': '默认',
    'Export to clipboard': '导出到剪贴板',
    'UNDEFINED': '未定义',
    'Save': '保存',
    'Import': '导入',
    'HARD RESET': '硬重置',
    'The Prestige Tree Modfinder': '声望树修改器',
    'Changelog': '更新日志',
    'Acknowledgements': '鸣谢',
    'a mod of The Prestige Tree made by Jacorb and Aarex': 'Jacorb和Aarex制作的The Prestige Tree的mod',
    'wall of text saying I do not own most of this': '文字墙说我不拥有大部分',
    'using The Modding Tree': '使用改装树',
    'This is made entirely for entertainment and parody purposes, no income is generated from this nor it\'s made to steal anybody\'s original works.': '这完全是出于娱乐和模仿目的而制作的，因此不会产生任何收入，也不会窃取任何人的原创作品。',
    'suggest everything and talk about how bad this mod is here': '建议一切并谈论这个mod有多糟糕',
    'in case you\'re already sick of this': '万一你已经厌倦了这个',
    'see what happened throughout this thing\'s history': '看看这件事的历史发生了什么',
    'Hotkeys': '快捷键',
    'Time Boosters': '时间增强器',
    'Beginner tip: Hold T to automatically absorb Time Power': '初学者提示：按住T可自动转生获得时间力量',
    'You have': '你有',
    'The Prestreestuck': '创世声望树',
    'The Modding Tree Discord': '改装树Discord',
    'The game is currently being updated.': '游戏正在更新中。',
    'Please check the Discord to see if there are new content updates!': '请检查Discord，看看是否有新的内容更新！',
    'Main Prestige Tree server': '主声望树服务器',
    'Time Power boosts point gain.': '时间力量加成点数获取。',
    'You total amount of Time Multipliers boosts your point gain.': '根据你拥有的时间加倍器总数加成你的点数获取。',
    'Space Power boosts Time Power gain.': '空间力量加成时间力量获得量。',
    'Add another Time Booster that reduces the price of the previous one.': '增加一个额外的时间增强器，它也可以降低前一个时间增强器的价格。',
    'Mind Power boosts Time Power gain.': '精神力量加成时间力量获得量。',
    'Heart Power boosts Time Power gain.': '心灵力量加成时间力量获得量。',
    "Space Accelerator": "空间加速器",
    'Points boost point gain.': '点数加成点数获得量。',
    'Gain 10% of your Time Power gain on absorb per second.': '每秒获得10%当前转生可获得的时间力量。',
    'Your Space Power gain on absorb boosts point gain.': '重置可获得空间力量加成点数获取',
    'Automatically max-upgrades your Time Multipliers for you every tick.': '每一刻都会自动购买所有时间加倍器。',
    'Adds upgrades to the Time layer': '在时间层级内增加新的升级。',
    "Automatically get Time Boosters for you every tick.": "每一刻都会自动购买时间增强器。 ",
    'Unspent Space Power boosts point gain.': '未使用的空间力量加成点数获得量。',
    'Faster Time Power generation based on Space Power.': '根据空间力量加速时间力量获取。',
    'Time Power boosts Space Power gain.': '时间力量加成空间力量获得量。',
    'Autobuyer prioritizes later Time Multipliers instead of earlier ones.': '自动购买者购买时间加倍器时倾向于先购买后面的。',
    '\^1.08 all Time Boosters effect.': '^1.08所有时间增强器效果。',
    'Autobuyer prioitizes Time Boosters instead of Time Multipliers.': '自动购买者倾向于先购买时间增强器而不是加倍器。',
    'Adds more upgrades to the Time layer.': '在时间层级内增加更多新的升级。',
    'Buys 1 of each Space Generators and Space Accelerators per tick.': '每一刻自动购买每一个空间发生器和加速器。',
    'Automatically buys Time upgrades.': '自动购买时间升级。',
    'Automatically get Time Booster\^2s.': '自动购买时间增强器^2。',
    'You keep your 2nd, 4th, 6th, 8th, 10th, and 12th Space upgrades on Mind Power absorb.': '精神重置后你可以保留第2，4，6，8，10，12项空间升级',
    'You keep your 1st, 3nd, and 5th Space upgrades on Mind Power absorb.': '精神重置后你可以保留第1，3，5项空间升级',
    'You keep your 7th, 9th, and 11th Space upgrades on Mind Power absorb.': '精神重置后你可以保留第7，9，11项空间升级',
    'Gain 5% of your Space Power gain on absorb per second.': '每秒获得空间重置可获得的5%空间力量',
    'You keep your forth row of Space upgrades on Mind Power absorb.': '精神重置后你可以保留第四排空间升级',
    'Unlocks Mind Upgrades.': '解锁精神升级',
    'Gain 5% of your Mind Power gain on absorb per second.': '每秒获得精神重置可获得的5%精神力量',
    'Mind Power boost point gain.': '心灵力量加成点数获得量',
    'Mind Power boost Time Power gain.': '心灵力量加成时间力量获得量',
    'Mind Power boost Space Power gain.': '心灵力量加成空间力量获得量',
    'Mind Power boosts all Space Generators.': '心灵力量加成所有空间发生器',
    'Getting Time Boosters no longer resets anything.': '购买时间增强器不再重置任何东西',
    'Multiplier from Time Boosters boosts point gain.': '时间增强器提供的加倍器加成点数',
    'which are boosting point gain by ×e': '可以加成点数获得量 ×e',
    'which are boosting point gain by ×ee': '可以加成点数获得量 ×ee',
    'which are boosting Mind Power gain by ×e': '可以加成精神力量获得量 ×e',
    'which are boosting Heart Power gain by ×e': '可以加成心灵力量获得量 ×e',
    'Points boost Heart Power gain.': '点数加成心灵力量获得量',
    'Time Power boosts Heart Power gain.': '时间力量加成心灵力量获得量',
    'Space Power boosts Heart Power gain.': '空间力量加成心灵力量获得量',
    'Space boosts Heart Power gain.': '空间加成心灵力量获得量',
    'Time Generators and Space Multipliers don\'t take anything away.': '时间加倍器和空间发生器不再消耗任何东西',
    'You keep your 1st, 3rd, and 5th Space upgrade on Heart Power absorb.': '心灵重置后你可以保留第1，3，5项空间升级',
    'You keep your 7th, 9th, and 11th Space upgrade on Heart Power absorb.': '心灵重置后你可以保留第7，9，11项空间升级',
    'You keep your 2nd, 4th, 6th, 8th, 10th, and 12th Space upgrade on Heart Power absorb.': '心灵重置后你可以保留第2，4，6，8，10，12项空间升级',
    'You keep your fourth row of Space upgrades on Heart Power absorb.': '心灵重置后你可以保留第四排空间升级',
    'Unlocks Heart Upgrades.': '解锁心灵升级',
    'Gain 5% of your Heart Power gain on absorb per second.': '每秒获得心灵重置可获得的5%心灵力量',
    'Buying an upgrade increases the cost of the upgrades in the same row.': '购买任意一项升级会提升同行其它升级的价格',
    'Buying Time Gens and Accelerators buys max instead of buy once. Also affects autobuyers.': '购买时间生产和加速可以最大购买，对自动购买也有效',
    'You need to buy at least one upgrade in the upper row before you can buy upgrades at that row.': '你必须至少购买一个上一行的升级才能购买下一行的升级',
    'Respecing Hope Upgrades does not give your Hope Power back!': '重置希望升级并不会返还心灵力量！',
    'Respec Hope Upgrades': '重置希望升级',
    'Points decrease the requirements for Hope and Rage resets.': '点数降低希望和愤怒的重置需求',
    'The upgrade above boosts point gain.': '上方升级也加成点数获得量',
    'The upgrade above boosts Time Power gain.': '上方升级也加成时间力量获得量',
    'The upgrade above boosts Space Power gain.': '上方升级也加成空间力量获得量',
    'Hope and Rage Essence boosts Mind and Heart Power gain.': '希望和愤怒精华加成心灵和精神力量获得量',
    'Hope and Rage Essence boosts Space Power gain.': '希望和愤怒精华加成空间力量获得量',
    'Hope and Rage Essence boosts Time Power gain.': '希望和愤怒精华加成时间力量获得量',
    'Hope and Rage Essence boosts point gain.': '希望和愤怒精华加成点数获得量',
    'Reduces the Hope Essence requirements by 1e12.': '希望精华需求降低1e12',
    'Reduces the Rage Essence requirements by 1e10.': '希望精华需求降低1e10',
    'Void Power boosts Light Power gain': '虚空力量加成光明力量获得量',
    'Light Power boosts Void Power gain': '光明力量加成虚空力量获得量',
    'Light Power and Void Power boosts point gain': '光明力量和虚空力量加成点数获得量',
    'Gets all Space upgrades and the first six Mind\/Heart milestones on Hope reset.': '希望重置后你可以保留所有空间升级和前六个心灵/精神里程碑',
    'Unlocks Hope upgrades.': '解锁希望升级',
    'Gives you all Heart and Mind upgrades and their seventh milestone on Hope reset.': '希望重置后你可以保留所有心灵/精神升级和它们的第七个里程碑',
    'Automatically do Rage resets.': '自动进行愤怒重置',
    'Gets all Space upgrades and the first six Mind\/Heart milestone on Rage reset.': '愤怒重置后你可以保留所有空间升级和前六个心灵/精神里程碑',
    'Unlocks Rage challenges.': '解锁愤怒挑战',
    'Gives you all Heart and Mind upgrades and their seventh milestone on Rage reset.': '愤怒重置后你可以保留所有心灵/精神升级和它们的第七个里程碑',
    'Automatically do Hope resets.': '自动进行希望重置',
    'Points decrease the requirement for Rage Essence and Hope Essence absorb.': '点数降低愤怒精华和希望精华的重置需求',
    'Rage Essence and Hope Essence boosts Time Power gain.': '愤怒精华和希望精华加成时间力量获得量',
    'Rage Essence and Hope Essence boosts Space Power gain.': '愤怒精华和希望精华加成空间力量获得量',
    'Reduces the requirements of the first three challenges.': '降低前三个挑战的需求',
    'Keeps all Hope and Rage milestones on Void resets.': '虚空重置后你可以保留所有希望和愤怒的里程碑',
    'Keeps Rage challenges on Void and Light resets.': '虚空重置和光明重置后你可以保留所有愤怒挑战进度',
    'Keeps Hope upgrades on Void and Light resets.': '虚空重置和光明重置后你可以保留所有希望升级',
    'Unlocks more Hope upgrades.': '解锁更多希望升级',
    'Gain 10% of your Void Power gain on absorb every second.': '每秒获得虚空重置可获得的10%虚空力量',
    'which are multiplying the base exponent of each Light Researches by ×': '使所有光明研究的基础指数×',
    'Keeps all Hope and Rage milestones on Light resets. This is already getting repetitive.': '光明重置后你可以保留所有希望和愤怒里程碑.这个好像重复了？',
    'Automatically toggles Hope and Rage Essence auto-reset on.': '自动把自动重置希望和自动重置愤怒的开关打开',
    'Absorbing Hope and Rage Essence doesn\'t reset anything. This does not apply to Rage Challenges though.': '希望和愤怒精华重置不再重置任何东西，但这个对愤怒挑战没有效果',
    'Unlocks a new aspect layer.': '解锁一个新的不同的层级',
    'Get 10% of your current Light Power gain per second.': '每秒获得光明重置可获得的10%光明力量',
    'Keeps all Light and Void milestones on Life resets.': '生命重置后你可以保留所有光明和虚空里程碑',
    'Keeps 350 levels of each Light Discovery on resets.': '重置后可以保留每项光明研究350级',
    'Gets 2% of your current Life Power gain on absorb per second. Also adds a new minigame into the Skaia layer to make the waiting worth it.': '每秒获得2%生命重置可获得的生命力量，增加一个迷你游戏到斯卡亚层级确保你不会因为没事做而无聊',
    'Unlocks Blessing (a.k.a. temporary boosts).': '解锁祝福(也可以叫它临时加成)',
    'Unlocks an aspect layer.': '解锁一个不同的层级',
    'Keeps all Life, Light, Void, Hope and Rage milestones on Doom resets.': '灾厄重置后你可以保留所有生命、光明、虚空、希望和愤怒的里程碑',
    'Keeps all Mind and Heart milestones and upgrades, Hope upgrades and Rage challenges on Doom resets.': '灾厄重置后你可以保留所有心灵和精神的里程碑和升级，以及希望升级和愤怒的挑战进度',
    'Keeps all Space upgrades on Doom resets.': '灾厄重置后你可以保留所有空间升级',
    'Gets 5% of your Doom Power gain on reset per second.': '每秒获得5%灾厄重置可获得的灾厄力量',
    'Unlocks a new Tab (no not the drink).': '解锁一个新的面板(tab)，不，不是毒品(tab)',
    'You can bulk absorb Hope and Rage Essence. Why don\'t this appear sooner you might ask? Because the game went fine without it.': '你可以批量购买希望和愤怒精华，你可能会想为什么现在才出来？因为没有它的时候游戏也在正常进行',
    'All challenges completed!': '所有挑战已经完成！',
    'You cannot access any layer below this one. Their upgrades and milestones effect still exists though. Basically you\'ll have to play blind.': '你无法看到除了这个层级以外的其它层级，但它们仍然在运作，也就是说你无法操作它们',
    'The minimum number of levels of each Light Discoveries is increased to 1,000,000 instead of 350.': '重置后获得的光明研究等级从350提升到1,000,000',
    'Raises the effect of the first Time upgrade by 5, after the softcaps. And yes, you should be able to continue doing this challenge for more rewards.': '提高前五个时间升级5倍，不受软上限影响，并且没错，你需要继续做这个挑战解锁更多奖励',
    'Squares the second Time upgrade\'s effect. You still have a long way to go.': '第二个时间升级的效果被平方，你还有很长的路要走',
    'Cubes the first Void Enhancement\'s effect. That\'ll make it more interesting.': '第一个虚空增幅的效果被立方，这会使它更有趣',
    'Squares the fourth Time upgrade\'s effect. Wow, who could have thought of that?': '第四个时间升级的效果被平方，天哪，谁能想到这个',
    'Tesseracts all of the second row of Time upgrades\' effect. Wow, such boost, much synergy.': '所有第二排时间升级的效果被四次方，天哪，如此强大，更多的协同效应',
    'Increases the maximum number of challenges you can do per each Rage Challenge from 5 to 10.': '愤怒挑战的最大次数从5提升到10',
    'Okay, you\'re almost there. Complete this challenge to give yourself a \^1.05 boost to point gain!': '好吧，你快完成了，完成这个挑战将使点数获取提高^1.05',
    'This is the last one. Complete this challenge to get 2 more wraths to conquer \>\:D': '这个就是最后了，完成这个挑战获得两个新的盛怒挑战>:D',
    'Raises the effect of the first Hope Upgrade by \^1.1.': '提升第一项希望升级的效果^1.1',
    'Squares the effect of the first Mind and Heart upgrade.': '第一项心灵和精神升级的效果被平方',
    'Triple tesseracts \(a.k.a 64\-cube or \^64\) the effect of the third row of Hope upgrades.': '第三排希望升级的效果进行三次的四次方(也就是^64)',
    'Cubes the effect of the first Time Upgrade. Yes, I know we\'ve done this before.': '第一项时间升级的效果被立方，对，我懂，我们之前做过这个',
    'Cubes the effect of fifth row of Hope upgrades.': '第五排希望升级的效果被立方',
    'Cubes the effect of the first Space upgrade.': '第一项空间升级的效果被立方',
    'Tesseracts the effect of the third Space upgrade.': '第三项空间升级的效果被四次方',
    'Tesseracts the effect of the seventh Space upgrade.': '第七项空间升级的效果被四次方',
    'Cubes the effect of the ninth Space upgrade.': '第九项空间升级的效果被立方',
    'Well, since everything is automated now, I don\'t think this is a challenge anymore. Squares all of the second row of Hope Upgrades\' effect.': '好吧，现在所有东西都自动了，我觉得这不算是挑战了。第二排希望升级的效果被平方',
    'Well, this is the last challenge for you. Unlocks new layers.': '好吧，这是最后一个挑战，用来解锁新层级',
    'Automatically toggles the \"automatically toggles Hope and Rage Essence auto-reset\" toggle on.': '自动把“自动开启希望和愤怒精华自动重置”开关打开',
    'Starts with 413 levels of the first Void Enhancement.': '重置后可以保留413级第一项虚空增幅',
    'Automatically turn all of the Life Blessing on. Well, we don\'t need to actually disable it atm.': '自动开启所有生命祝福，也对，我们并不需要关闭它',
    'which are boosting all exponential effects on all Blood Synergizers by ×': '增强所有鲜血协同器的指数效果×',
    'which are boosting your first Void Enhancement\'s effect by ×': '增强第一项虚空增幅的效果×',
    'Do a Hope reset.': '进行一次希望重置',
    'Do a Rage reset.': '进行一次愤怒重置',
    'Complete a Rage Challenge.': '完成一个愤怒挑战',
    'Complete a Light Research.': '完成一个光明研究',
    'Complete a Void Enhancement.': '完成一个虚空增幅',
    'note: your boondollars will be taxed \(a.k.a. decays\) after 1e10 of them!': '注意：你的恩惠币超过1e10后会开始持续抽税(或者是腐烂)！',
    'Your Porkhollow is containing': '你的空灵猪肉产出',
    'Porkhollow': '空灵猪',
    'You can bulk absorb Breath and Blood Essence.': '你可以批量重置呼吸和鲜血精华',
    'Buy': '购买',
    'Sell': '出售',
    'Savings': '设置',
    'Display': '显示',
    'Color Theme: Default': '主题色调：无',
    'Color Theme: Aqua': '主题色调：海洋',
    'Color Theme: The Felt': '主题色调：新感觉',
    'Color Theme: Trickster': '主题色调：欺诈',
    'All Save States': '所有存档',
    'which are boosting all Active Classes effects based on your Class Points.': '根据你的课程点数加成所有激活的课程',
    'which are boosting all Aspect Essence effects based on all Aspect Shards, with their own aspect also gets a bonus based on its Aspect Power.': '根据你所有的相位碎片加成你所有的相位精华效果，同时它们还分别加成自身对应的相位力量',
    'which are boosting all Aspect Essence effects based on the Aspect Essence of their counterpart aspect.': '根据你的相位精华加成与自身对立的相位精华效果',
    'which are boosting all Aspect Powers effects based on other Aspect Powers that\'s not themselves, after the softcaps.': '根据其他相位力量加成相位力量效果(不包含自身)，在软上限之后加成',
    'which are boosting all Aspect Powers effects based on themselves, after the softcaps.': '根据自身相位力量加成相位力量效果，在软上限之后加成',
    'which are boosting all Aspect Shards effects based on all Aspect Powers, but their own aspect is only as half as effective.': '根据所有相位力量加成所有相位碎片效果，但它们对自身的加成只有一半效果',
    'which are boosting all Passive Classes effects based on your Class Points.': '根据你的课程点数加成所有被动的课程',
    'which are decrasing all Aspect Essence costs based on their own Aspect Power, but the effect fluctuates over time.': '根据自身的相位力量降低所有相位精华的价格，但这个数值会随时间波动',
    'which are decreasing all Aspect Powers costs based on other Aspect Powers that\'s not themselves.': '根据其他相位力量降低相位力量的价格(不包含自身)',
    'which are decreasing all Aspect Powers costs based on themselves.': '根据自身相位力量降低相位力量的价格',
    'which are decreasing all Aspect Shards costs based on all Aspect Powers, with their own being thrice as effective.': '根据所有相位力量降低所有相位碎片的价格，它们对自身的加成有三倍效果',
    'which are decreasing all Aspect Shards costs based on other Aspect Shards that\'s not themselves.': '根据其他相位碎片降低相位碎片的价格(不包含自身)',
    'which are boosting all Aspect Shards effects based on themselves.': '根据所有相位碎片加成它们自身的效果',
    'which are decreasing all Aspect Essence costs based on all Aspect Powers, with their own aspect also gets a bonus based on its Aspect Shards.': '根据所有相位力量降低所有相位精华的价格，同时它们自身的相位碎片也会增强对自身的效果',
    "Dersite Blue Symphony": "蓝色神恩交响曲",
    "Dersite Bronze Symphony": "铜色神恩交响曲",
    "Dersite Fuchsia Symphony": "紫红色神恩交响曲",
    "Dersite Gold Symphony": "金色神恩交响曲",
    "Dersite Indigo Symphony": "靛蓝色神恩交响曲",
    "Dersite Jade Symphony": "玉色神恩交响曲",
    "Dersite Lime Symphony": "石灰色神恩交响曲",
    "Dersite Olive Symphony": "橄榄色神恩交响曲",
    "Dersite Purple Symphony": "紫色神恩交响曲",
    "Dersite Rust Symphony": "锈色神恩交响曲",
    "Dersite Teal Symphony": "蓝绿色神恩交响曲",
    "Dersite Violet Symphony": "紫罗兰色神恩交响曲",
    "Prospitian Blue Symphony": "蓝色真实交响曲",
    "Prospitian Bronze Symphony": "铜色真实交响曲",
    "Prospitian Fuchsia Symphony": "紫红色真实交响曲",
    "Prospitian Gold Symphony": "金色真实交响曲",
    "Prospitian Indigo Symphony": "靛蓝色真实交响曲",
    "Prospitian Jade Symphony": "玉色真实交响曲",
    "Prospitian Lime Symphony": "石灰色真实交响曲",
    "Prospitian Olive Symphony": "橄榄色真实交响曲",
    "Prospitian Purple Symphony": "紫色真实交响曲",
    "Prospitian Rust Symphony": "锈色真实交响曲",
    "Prospitian Teal Symphony": "蓝绿色真实交响曲",
    "Prospitian Violet Symphony": "紫罗兰色真实交响曲",
    'All Rust sign effects boost Class Point gain.': '所有锈色符文效果都可以提高课程点获取量',
    'All Rust sign effects boosts Class Point gain.': '所有锈色符文效果都可以提高课程点获取量',
    'All Bronze sign effects boost all Aspect Point effects.': '所有铜色符文效果都可以提高所有相位点的效果',
    'All Gold sign effects boost the Prospit Point effect.': '所有金色符文效果都可以提高真实点数效果',
    'All Gold sign effects boost the Derse Point effect.': '所有金色符文效果都可以提高神恩点数效果',
    'All Lime sign effects decrease the Prospit Point requirement.': '所有石灰色符文效果都可以降低真实点的重置需求',
    'All Lime sign effects decrease the Derse Point requirement.': '所有石灰色符文效果都可以降低神恩点的重置需求',
    'All Olive sign effects boost the Derse Point effect.': '所有橄榄色符文效果都可以提高神恩点的效果',
    'All Olive sign effects boost the Prospit Point effect.': '所有橄榄色符文效果都可以提高真实点的效果',
    'All Jade sign effects boost Aspect Point gain,': '所有玉色符文效果都可以提高相位点获取量，',
    'All Teal sign effects boost all of the second row of Skaia upgrades.': '所有蓝绿色符文效果都可以提高斯卡亚第二行的所有升级效果',
    'All Blue sign effects boost the sixth and eighth row Skaia upgrades.': '所有蓝色符文效果都可以提高斯卡亚第六行和第八行的所有升级效果',
    'All Indigo sign effects boost the sixth row Skaia upgrade, except stronger.': '所有靛蓝色符文效果都可以提高斯卡亚第六行升级效果，这个更强',
    'All Purple sign effects boost Muse Power effect.': '所有紫色符文效果都可以提高缪斯力量的效果',
    'All Violet sign effects boost Lord Power effect.': '所有紫罗兰色符文效果都可以提高上帝力量的效果',
    'All Fuchsia sign effects boost all Derse sign gains.': '所有紫红色符文效果都可以提高所有神恩符文的获取量',
    'All Fuchsia sign effects boost all Prospit sign gains.': '所有紫红色符文效果都可以提高所有真实符文的获取量',
    'massively.': '效果极强',
    'Abolishments': '废弃符文',
    'Requires: e': '需要：e',
    '': '',
    '': '',

    //谚语
    'ALTERNATE PROGRESSION': '交替级数',
    'THATS NOT VERY CREATIVE': '那不是很创意',
    'COOL AND NEW PRESTIGE TREE': '酷和新的声望树',
    'COOL AND NEW INCREMENTAL GAME': '很酷的新增量游戏',
    'CLASS POINTS CUBED': '课程点的立方',
    'CLASS POINTS INFINITED CUBED': '课程点无限的立方',
    'CLASS POINTS CUBED SQUARED': '课程点的立方的平方',
    'CLASS POINTS INFINITED HEXERACTED': '课程点无尽的六次方',
    'CLASS POINTS INFINITED PENTERACTED': '课程点无尽的五次方',
    'CLASS POINTS SQUARED': '课程点的平方',
    'CLASS POINTS INFINITED TESSERACTED': '课程点无尽的四次方',
    'CLASS POINTS SQUARED SQUARED': '课程点平方的平方',
    'CLASS POINTS TESSERACTED': '课程点的四次方',
    'CLASS POINTS TESSERACTED SQUARED': '课程点的四次方的平方',
    'FULLY REFURBISHED': '全面翻新',
    'FASTER LEVEL UPS': '更快级别的UPS',
    'CARAPACIPHONY': '卡拉帕尼',
    'CLASSPHONY': '上流社会',
    'PROGRESSION CUBED': '进阶的立方',
    'PROGRESSION SQUARED': '进阶的平方',
    'IT CAN NOT BE UNDONE': '无法撤消',
    'IT IS TOO LATE TO DO ANYTHING ELSE': '一切都太迟了',
    'IT MUST HAPPENS': '它必须发生',
    'JUST A LITTLE BIT MORE': '只是多了一点点',
    'THE ASCENSION IS ALMOST HERE': '几乎到了这里',
    'EVERYTHING IS ACTIVE': '全部激活了',
    'EVERYTHING IS ALMOST READY': '一切都准备好了',
    'REPLACING ALL THE PROCESS': '替换所有的进度',
    'FULLY POWERED': '电已充满',
    'AGE OF GROWTH': '成长时代',
    'SIGNPHONY': '招牌',
    'SPECIAL TREATMENT': '特别待遇',
    'SWAYPHONY': '斯旺·霍尼',
    'THE HEMO ERA': '血统时代',
    'ALMOST THE ENTIRE UPGRADE PANEL': '基本上是所有的升级面板',
    'WAIT THIS ISNT HOMESTUCK': '等等这不是HOMESTUCK',
    'REMOVE CARPAL TUNNEL': '移除腕管',
    'IS THIS THING A JOKE': '你在开玩笑吗',
    'REMOVE CARPAL TUNNEL AGAIN': '再次移除腕管',
    'ADD SOMETHING TO THE GAME': '在游戏里添加些东西',
    'REMOVE MORE CARPAL TUNNEL': '移除更多腕管',
    'NO I MEAN THE HOMESTUCK SOMETHING': '现在我稍微理解HOMESTUCK',
    'TIME IS FASTER BASED ON SPACE': '空间会使时间加速',
    'TIME IS BOOSTING SPACE': '时间会加成空间',
    'RECONSTRUCT STRATEGY': '重新调整策略',
    'INCREASE BOOSTING EFFICIENCY': '增强增强器效果',
    'ALSO RECONSTRUCT STRATEGY': '再次调整策略',
    'A REPLACEMENT UPGRADE': '一个升级的替代品',
    'AUTOMATE SPACE GENERATORS': '自动空间发生器',
    'FINALLY UPGRADES AUTOBUYERS': '最后的升级自动化',
    'TIME AUTO BOOSTER SQUARED': '时间自动购买者被平方了',
    'USE THE TIME POWER': '掌握时间力量',
    'POWER THE TIME': '赋予时间力量',
    'DILATE THE TIME CONTINUUM': '增强时间连续性',
    'SPACE IS BOOSTING TIME': '空间增强时间',
    'THIS IS BORING': '这玩意真无聊',
    'MIND IS BOOSTING TIME': '精神增强时间',
    'HEART IS BOOSTING TIME': '心灵增强时间',
    'NOW WITH MORE IDLE': '现在需要更多的放置',
    'WORRY ABOUT UPGRADES LESS': '为升级不够多而发愁',
    'SUSPICIOUSLY SIMILAR MILESTONE': '一个可疑的相似的里程碑',
    'WORRY LESS ABOUT UPGRADES AGAIN': '再次为升级不够多而发愁',
    'EXPAND YOUR MIND': '解放你的精神',
    'THE BALNCE IS BROKEN': '打破平衡',
    'MIND BOOSTS POINTS': '精神加成点数',
    'MIND BOOSTS TIME': '精神加成时间',
    'MIND BOOSTS SPACE': '精神加成空间',
    'MIND BOOSTS SPACE AGAIN': '精神再次加成空间',
    'THESE ARE GIVING ME EPILEPSY': '这些东西令我疯狂',
    'POINT BOOSTERS': '点数增强者',
    'RESET PROOFING': '重新校对',
    'POINTS BOOST HEART': '点数加成心灵',
    'TIME BOOSTS HEART': '时间加成心灵',
    'SPACE BOOSTS HEART': '空间加成心灵',
    'SPACE BOOSTS HEART AGAIN': '空间再次加成心灵',
    'BETTER SCALING': '更好的购买方式',
    'EVEN LESS JITTERING': '不必再操心了',
    'BOOSTING PRODUCTION': '加成生产器',
    'A QUALITY OF LIFE MILESTONE': '提高生活质量的里程碑',
    'WHY ISNT THIS FIRST': '为什么这个不是第一个',
    'OPEN THEE HEART': '敞开心灵',
    'NO LONGER BALANCED': '再也没有平衡了',
    'PLAYER': '玩家',
    'IF YOU CAN': '如果你可以',
    'SEE THIS': '看见这个',
    'THAT MEANS': '那就说明',
    'YOUVE PLAYED ENOUGH': '你已经玩了足够多',
    'TO BE ABLE TO': '从而可以',
    'MAKE DECISIONS': '做出决定',
    'FOR YOURSELF': '为你自己',
    'YOU ARE NOW': '你现在是',
    'A SKILLED PLAYER': '专业玩家',
    'AS SUCH': '如此专业',
    'YOU ARE ENTITLED': '你有权利',
    'TO WHAT HAPPENS': '了解一下',
    'DURING YOUR JOURNEY': '发生了什么',
    'I AM SO': '我非常',
    'SO PROUD': '非常骄傲',
    'OF YOU': '为你骄傲',
    'HOPES AND DREAMS': '梦与希望',
    'UPGRADES AND JUSTICE': '升级与正义',
    'UNEXPECTED SYNERGY': '意料之外的配合',
    'RAGEFUL HOPE': '满溢愤怒的希望',
    'BRINGER OF CHAOS': '混沌使者',
    'COMMENCE DESTRUCTION': '毁灭开始',
    'HOPEFUL RAGE': '充满希望的愤怒',
    'GET TO THE POINT': '切入“重点”',
    'TIME DILATION': '时间膨胀',
    'SPACE EXPANSION': '空间扩张',
    'TETRATION PROBLEM': '迭代运算问题',
    'NULL AND VOID': '空与虚',
    'VOID AND NULL': '虚与空',
    'NULL AND UNDEFINED': '空与未知',
    'VOID AND UNDEFINED': '虚与未知',
    'UNDEFINED AND UNDEFINED': '未知与未知',
    'LEVELS OF VOID': '虚等级',
    'LEVELS OF NULL': '空等级',
    'LIGHT THE WAY': '照亮道路',
    'METAAUTOMATOR': '完整的自动化',
    'LOSSLESS ABSORBTION': '无损的重置',
    'NOT SO LOYAL COMPANION': '不太忠诚的同伴',
    'SUNSHINE': '阳光',
    'BLESSING OF LIFE SQUARED': '平方生命的祝福',
    'BLESSING OF LIFE CUBED': '三次方生命的祝福',
    'INSERT A LIFE MILESTONE NAME HERE': '在这里输入一个生命里程碑的名字',
    'EXTREMELY WONDERFUL COLOR SCHEME': '非常棒的配色方案',
    'NOW WE JUST HAVE TO WAIT': '现在我们只需要等待',
    'IT IS TIME': '是时候了',
    'THE ULTIMATE WRATH': '终焉的盛怒',
    'WHAT LAYERS': '什么是层级',
    'ONE HELL OF A WRATH': '盛怒的地狱',
    'END OF THE WORLD': '世界尽头',
    'PREPARE FOR EVACUATION': '准备撤离',
    'READY FOR THE PLAN': '构想计划',
    'IT IS ALMOST HERE': '几乎完成了',
    'GET READY FOR THE ULTIMATE WRATH': '为终焉的盛怒做好了准备',
    'YOU CAN NOT ESCAPE': '你 跑 不 掉 了',
    'REACH BEYOND THE CIRCLE.': '超越这个圆',
    'Need e1.000e216 points': '需要 e1.000e216 点数',
    'COMMENCER OF DESTRUCTION': '招来毁灭',
    'LIGHT THE FUTURE': '照亮未来',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //原样
//    'Act': '相位',
//    'A': '相',
//    'C': '阶',
//    'P': '赞',
//    'D': '德',
    '×e': '×e',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    'Time Booster\^2s no longer resets, and its multi boosts Time Power gain.': '时间增强器^2不再重置，并且它还会加成时间力量',
    "Space Generators act as if they're bought 10× when you only buy once. Buying this does a forced Heart reset.": "空间发生器一次性购买十个，购买这个会强制进行一次心灵重置",
    "Time Boosters scale less and worth more.": "时间增强器涨价更慢且效果更强。",
    "Time Boosters": "时间增强器",
    "Time Played: ": "游戏时长：",
    "based on Homestuck by Andrew Hussie (of course)": "基于Andrew Hussie的Homestuck（当然）",
    "Offline Prod: ": "离线产出: ",
    "Theme: ": "主题: ",
    "Autosave: ": "自动保存: ",
    "Completed Challenges: ": "完成的挑战：",
    "High-Quality Tree: ": "高质量树：",
    "Show Milestones: ": "显示里程碑：",
    "All of your Class Powers are giving you ": "您所有的阶级力量都给您 ",
    "Req: ": "需要: ",
    "You gain Class Points faster based on your ": "你获得课程点数更快，基于你的",
    "Boosts all of the second upgrade row effect, based on ": "提升所有的第二升级行效果，基于",
    "Replace the process of getting Aspect ": "替换得到相位的过程",
    'which are boosting point gain by ×': '可以加成点数获得量 ×',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "9.869e598/s).": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Time Power\n			": "时间力量",
    "Space\n			": "空间",
    "Space power": "空间力量",
    "If you can see this message, that means the game has detected inconsistent version number between files.": "如果您看到此消息，则表明游戏检测到文件之间的版本号不一致。",
    "Please try again later, or if this screen has been up for more than 30 minutes, please contact the mod author.": "请稍后再试，或者如果该屏幕显示超过30分钟，请与mod作者联系。",
    "This can be caused by the website currently being updated and not ready yet or there is an error causing the files to be read incorrectly.": "这可能是由于当前正在更新的网站尚未准备就绪引起的，或者是由于错误导致文件读取不正确。",
    "If you can see this something bad must've happened!": "如果您看到此错误，则必定发生了坏事！",
    "Massive Slowdown": "大规模减速",
    " Dersites": " 神恩力量",
    " Prospitians": " Prospitians",
    " Class Points per second.": " 课程点每秒。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^(.+)直到下一个回切点$/, 
    /^÷(.+),$/, 
    /^(.+)x$/, 
    /^e(.+)\/秒$/, 
    ///^(.+)√$/, 
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^(\d+) layers remaining$/, '$1 层剩余'],
    [/^and will need (.+) Echepoints to climb to the next rung.$/, '并且需要$1个阶层点才能提升到下一个阶层。'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^which are boosting your Aspect Point gain by ×(.+).\n(.+)Cost: (.+) points$/, '使你的相位点获取量增加$1\n成本：$3 点'],
    [/^which are raising the effect of Time Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的时间力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Time Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的时间力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Space Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的空间力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Space Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的空间力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Mind Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的精神力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Mind Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的精神力量价格的变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Heart Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的心灵力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Heart Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的心灵力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Rage Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的愤怒力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Rage Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的愤怒力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Hope Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的希望力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Hope Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的希望力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Void Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的虚空力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Void Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的虚空力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Light Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的光明力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Light Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的光明力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Life Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的生命力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Life Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的生命力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Doom Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的灾厄力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Doom Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的灾厄力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Blood Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的鲜血力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Blood Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的鲜血力量的价格变为^$1\n成本：$3 相位点'],
    [/^which are raising the effect of Breath Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的呼吸力量的效果变为^$1\n成本：$3 相位点'],
    [/^which are raising the cost of Breath Power by \^(.+).\n(.+)Cost: (.+) Aspect Points$/, '使你的呼吸力量的价格变为^$1\n成本：$3 相位点'],
    [/^Power by (.+).\n(.+)Cost: (.+) Aspect Points$/, '力量$1。\n成本：$3 相位点'],
    [/^Heir Power: \^(.+),$/, '继承人力量^$1,'],
    [/^Slyph Power: \^(.+),$/, '希尔芙力量^$1,'],
    [/^Seer Power: \^(.+),$/, '先知力量^$1,'],
    [/^Lord Power: \^(.+),$/, '上帝力量^$1,'],
    [/^Muse Power: \^(.+),$/, '缪斯力量^$1,'],
    [/^Prince Power: ×$/, '王子力量×'],
    [/^Page Power: \^(.+),$/, '历史力量^$1,'],
    [/^Maid Power: \^(.+),$/, '女仆力量^$1,'],
    [/^Bard Power: \^(.+),$/, '诗人力量^$1,'],
    [/^Thief Power: \^(.+),$/, '盗贼力量^$1,'],
    [/^Mage Power: \^(.+),$/, '法师力量^$1,'],
    [/^Witch Power: ×$/, '巫师力量×,'],
    [/^Rogue Power: \^(.+),$/, '游侠力量^$1,'],
    [/^Knight Power: \^(.+),$/, '骑士力量^$1,'],
    [/^which are giving you (.+) Dersites per second.$/, '每秒生产$1神恩力量'],
    [/^which are giving you (.+) Prospitians per second.$/, '每秒生产$1真实力量'],
    [/^Currently: ×(.+)$/, '当前：×$1'],
    [/^Currently: ÷(.+)$/, '当前：÷$1'],
    [/^Currently: \^(.+)$/, '当前：^$1'],
    [/^×(.+) Class Point gain$/, '×$1课程点获得量'],
    [/^(.+) Abolishments$/, '×$1废弃符文'],
    [/^(.+)× row gains$/, '×$1当前层收益'],
    [/^×(.+) Derse sign gains$/, '×$1神恩符文获得量'],
    [/^×(.+) Prospit sign gains$/, '×$1真实符文获得量'],
    [/^×(.+) all Aspect Point effects$/, '×$1所有相位点的效果'],
    [/^×(.+) Prospit Point effect$/, '×$1真实点的效果'],
    [/^×(.+) Derse Point effect$/, '×$1神恩点的效果'],
    [/^×(.+) Prospit Point effect$/, '×$1真实点的效果'],
    [/^×(.+) Muse Power effect$/, '×$1缪斯力量的效果'],
    [/^×(.+) Lord Power effect$/, '×$1上帝力量的效果'],
    [/^×(.+) sixth and eighth row Skaia upgrades$/, '×$1斯卡亚第六排和第八排的升级'],
    [/^×(.+) sixth row Skaia upgrade$/, '×$1斯卡亚第六排的升级'],
    [/^\^(.+) Aspect Point gain$/, '^$1相位点的获得量'],
    [/^\^(.+) second row of Skaia upgrades$/, '^$1斯卡亚第二排的所有升级'],
    [/^÷(.+) Prospit Point requirement$/, '÷$1真实点的重置需求'],
    [/^÷(.+) Derse Point requirement$/, '÷$1神恩点的重置需求'],
    [/^Level (.+)$/, '等级 $1'],
    [/^Hope: ×(.+)$/, '希望×$1'],
    [/^Time: ×(.+)$/, '时间×$1'],
    [/^Space: ×(.+)$/, '空间×$1'],
    [/^Rage: ×(.+)$/, '愤怒×$1'],
    [/^Mind: ×(.+)$/, '精神×$1'],
    [/^Heart: ×(.+)$/, '心灵×$1'],
    [/^Life: ×(.+)$/, '生命×$1'],
    [/^Doom: ×(.+)$/, '灾厄×$1'],
    [/^Void: ×(.+)$/, '虚空×$1'],
    [/^Light: ×(.+)$/, '光明×$1'],
    [/^Breath: ×(.+)$/, '呼吸×$1'],
    [/^Blood: ×(.+)$/, '鲜血×$1'],
    [/^Hope: (.+)$/, '希望$1'],
    [/^Time: (.+)$/, '时间$1'],
    [/^Space: (.+)$/, '空间$1'],
    [/^Rage: (.+)$/, '愤怒$1'],
    [/^Mind: (.+)$/, '精神$1'],
    [/^Heart: (.+)$/, '心灵$1'],
    [/^Life: (.+)$/, '生命$1'],
    [/^Doom: (.+)$/, '灾厄$1'],
    [/^Void: (.+)$/, '虚空$1'],
    [/^Light: (.+)$/, '光明$1'],
    [/^Breath: (.+)$/, '呼吸$1'],
    [/^Blood: (.+)$/, '鲜血$1'],
    [/^Hope: ÷(.+)$/, '希望÷$1'],
    [/^Time: ÷(.+)$/, '时间÷$1'],
    [/^Space: ÷(.+)$/, '空间÷$1'],
    [/^Rage: ÷(.+)$/, '愤怒÷$1'],
    [/^Mind: ÷(.+)$/, '精神÷$1'],
    [/^Heart: ÷(.+)$/, '心灵÷$1'],
    [/^Life: ÷(.+)$/, '生命÷$1'],
    [/^Doom: ÷(.+)$/, '灾厄÷$1'],
    [/^Void: ÷(.+)$/, '虚空÷$1'],
    [/^Light: ÷(.+)$/, '光明÷$1'],
    [/^Breath: ÷(.+)$/, '呼吸÷$1'],
    [/^Blood: ÷(.+)$/, '鲜血÷$1'],
    [/^which is equivalent to climbing (.+) Achievement Rungs on the Echeladder.$/, '这相当于攀登了$1个阶层。'],
    [/^(.+) Breath Essence & (.+) Blood Essence$/, '$1呼吸精华 \＆ $2鲜血精华'],
    [/^([\d\.,]+)$/, '$1'],
    [/^([\d\.,]+)x$/, '$1x'],
    [/^e([\d\.,]+)$/, 'e$1'],
    [/^ee([\d\.,]+)$/, 'ee$1'],
    [/^Next at (.+) point$/, '下一个在 $1 点'],
    [/^Goal: (.+)e(.+) points$/, '目标： $1e$2 点'],
    [/^\÷e(.+)e(.+) and \÷e(.+)e(.+), respectively.$/, '分别÷e$1e$2 和 ÷e$3e$4'],
    [/^\÷ee(.+) and \÷ee(.+), respectively.$/, '分别÷ee$1 和 ÷ee$2'],
    [/^Next at (.+) 点\n			$/, '下一个需要 $1 点'],
    [/^(.+) Mind Power\n			$/, '$1 精神力量'],
    [/^(.+) Hope Power\n			$/, '$1 希望力量'],
    [/^(.+) Mind Power\n			$/, '$1 精神力量'],
    [/^Point gain is softcapped beyond (.+)e(.+) points, with a magnitude of (.+).$/, '点数获取将在$1e$2到达软上限，影响级别为$3'],
    [/^Raises Time Power gain to the power of \^(.+)$/, '时间力量获得量变为^$1'],
    [/^Raises Space Power gain to the power of \^(.+)$/, '空间力量获得量变为^$1'],
    [/^Tetrates point gain by \^\^(.+)$/, '点数获得量变为^^$1'],
    [/^(.+) \/ (.+) completions$/, '$1 / $2 完成次数'],
    [/^Hope Power \(+e(.+)e(.+)\/s\).$/, '心灵力量 (+e$1e$2/s)'],
    [/^Idle \/ (.+)$/, '空闲 / $1'],
    [/^Idle \/ e(.+)$/, '空闲 / e$1'],
    [/^Idle \/ e(.+)e(.+)$/, '空闲 / e$1e$2'],
    [/^×e(.+),$/, '×e$1,'],
    [/^(.+) OOM\^(.+)s\/秒$/, '$1 OOM^$2s/秒'],
    [/^(.+) OOMs\/秒$/, '$1 OOMs/秒'],
    [/^(.+)Hope Essence$/, '$1心灵精华'],
    [/^(.+)Rage Essence$/, '$1愤怒精华'],
    [/^(.+)Mind Power$/, '$1精神力量'],
    [/^(.+)Heart Power$/, '$1心灵力量'],
    [/^(.+)Doom Power$/, '$1灾厄力量'],
    [/^(.+)\% on completion$/, '$1%阶层进度'],
    [/^(.+)Void Power$/, '$1虚空力量'],
    [/^(.+)Light Power$/, '$1光明力量'],
    [/^(.+)Life Power$/, '$1生命力量'],
    [/^(.+)Space Power$/, '$1空间力量'],
    [/^Current endgame: (.+) points$/, '当前的游戏终点：$1点'],
    [/^Cost: (.+) points$/, '成本：$1点'],
    [/^Cost: (.+) Class Points$/, '成本：$1课程点'],
    [/^or approximately (.+) boonmint\^(.+)s, whatever you prefer.$/, '或者大约$1恩惠币^$2，随你喜欢'],
    [/^or approximately (.+) boonmints, whatever you prefer.$/, '或者大约$1恩惠币，随你喜欢'],
    [/^boondollars \(+(.+)\/s\), which are giving a (.+)× boost to Life Point gain$/, '恩惠币(+$1/s)，可以增加$2×倍的生命力量获取量'],
    [/^which are boosting all Breath Synergizers\' gain by ×(.+)$/, '增强所有呼吸协同器的效果×$1'],
    [/^which are boosting all exponential effects on all Breath Synergizers by ×$/, '增强所有呼吸协同器的指数效果×'],
    [/^which are boosting all of your Time Multipliers\' effects by ×(.+)$/, '增强所有时间加倍器的效果×$1'],
    [/^which are boosting your Space Accelerator effect by ×(.+)$/, '增强空间加速器的效果×$1'],
    [/^which are boosting your Space Accelerator gain by ×(.+)$/, '增强空间加速器获取量×$1'],
    [/^which are boosting your Light Power gain by ×(.+)$/, '增强光明力量获取量×$1'],
    [/^which are boosting your Life Power gain by ×(.+)$/, '增强生命力量获取量×$1'],
    [/^which are boosting your Void Power gain by ×(.+)$/, '增强虚空力量获取量×$1'],
    [/^which are boosting all Blood Synergizers\' gain by ×(.+)$/, '增强所有鲜血协同器获取量×$1'],
    [/^which are boosting Doom Power's effect by \^$/, '增强灾厄力量的效果^'],
    [/^which are boosting your first Void Enhancement\’s effect by ×$/, '增强第一项虚空增幅的效果×'],
    [/^which are boosting your Doom Power gain by ×(.+)$/, '增强灾厄力量获取量×$1'],
    [/^which are boosting your Blood Power gain by ×(.+)$/, '增强鲜血力量获取量×$1'],
    [/^which are boosting all of your Light Discoveries effect by \^$/, '增强所有光明研究的效果^'],
    [/^which are boosting your first Life effect by \^$/, '增强第一项生命的效果^'],
    [/^which are boosting your first row of Mind upgrades\' effect by \^$/, '增强第一排精神升级的效果^'],
    [/^which are boosting your first Rage Challenge\'s effect by \^$/, '增强第一个愤怒挑战的效果^'],
    [/^which are boosting your second Rage Challenge\'s effect by \^$/, '增强第二个愤怒挑战的效果^'],
    [/^which are boosting your third Rage Challenge\'s effect by \^$/, '增强第三个愤怒挑战的效果^'],
    [/^which are boosting your first Hope upgrade\'s effect by \^$/, '增强第一个希望升级的效果^'],
    [/^which are boosting all of the third row of your Hope Upgrades\' effect by \^$/, '增强第三排所有希望升级的效果^'],
    [/^which are boosting all of the sixth row of your Hope Upgrades\' effect by \^$/, '增强第六排所有希望升级的效果^'],
    [/^which are boosting your second row of Mind upgrades\' effect by \^$/, '增强第二排精神升级的效果^'],
    [/^which are boosting your Mind Power gain by ×(.+)$/, '增强精神力量获取量×$1'],
    [/^which are boosting your first row of Heart upgrades\' effect by \^$/, '增强第一排心灵升级的效果^'],
    [/^which are boosting your first row of Heart upgrades\' effect \(again\) by \^$/, '增强第一排心灵升级的效果(再次)^'],
    [/^which are boosting your Heart Power gain by ×(.+)$/, '增强心灵力量获取量×$1'],
    [/^which are boosting all of your Space Generators by ×(.+)$/, '增强所有时间加倍器的效果×$1'],
    [/^which are boosting your Space Power gain by ×(.+)$/, '增强空间力量获取量×$1'],
    [/^which are boosting your Time Booster\'s effect by \^$/, '增强所有时间增强器的效果^'],
    [/^which are boosting your Time Booster\^2\'s effect by \^$/, '增强所有时间增强器^2的效果^'],
    [/^which are giving a ×(.+) boost to point gain.$/, '将提高×$1倍的点数获得量'],
    [/^which are giving (.+) Blood Power per second.$/, '将产生e$1鲜血力量每秒'],
    [/^which are giving (.+) Breath Power per second.$/, '将产生e$1呼吸力量每秒'],
    [/^which are decreasing the scaling point of Light Researches by (.+)$/, '使所有光明研究的涨价速度降低$1'],
    [/^which are giving a e(.+)× boost to point gain$/, '使你的点数获得量增加e$1×'],
    [/^which are giving a e(.+)× boost to Time Power gain$/, '使你的时间力量获得量增加e$1×'],
    [/^which are giving a e(.+)× boost to Space Power gain$/, '使你的空间力量获得量增加e$1×'],
    [/^which are giving a e(.+)× boost to Heart Power gain$/, '使你的心灵力量获得量增加e$1×'],
    [/^which are giving a e(.+)× boost to Mind Power gain$/, '使你的精神力量获得量增加e$1×'],
    [/^which are giving a (.+)× boost to point gain$/, '使你的点数获得量增加$1×'],
    [/^which are giving a (.+)× boost to Time Power gain$/, '使你的时间力量获得量增加$1×'],
    [/^which are giving a (.+)× boost to Space Power gain$/, '使你的空间力量获得量增加$1×'],
    [/^which are giving a (.+)× boost to Heart Power gain$/, '使你的心灵力量获得量增加$1×'],
    [/^which are giving a (.+)× boost to Mind Power gain$/, '使你的精神力量获得量增加$1×'],
    [/^which are giving a (.+)e(.+)× boost to point gain$/, '使你的点数获得量增加$1e$2×'],
    [/^which are giving a (.+)e(.+)× boost to Time Power gain$/, '使你的时间力量获得量增加$1e$2×'],
    [/^which are giving a (.+)e(.+)× boost to Space Power gain$/, '使你的空间力量获得量增加$1e$2×'],
    [/^which are giving a (.+)e(.+)× boost to Heart Power gain$/, '使你的心灵力量获得量增加$1e$2×'],
    [/^which are giving a (.+)e(.+)× boost to Mind Power gain$/, '使你的精神力量获得量增加$1e$2×'],
    [/^which are decreasing the Rage Essence requirement by ÷(.+)e(.+)$/, '使你的愤怒精华重置需求÷$1e$2'],
    [/^which are decreasing the Hope Essence requirement by ÷(.+)e(.+)$/, '使你的希望精华重置需求÷$1e$2'],
    [/^(.+) \/ (.+) Class Points(.+)\n(.+)$/, '$1 \/ $2 阶级点'],
    [/^You are getting (.+) Aspect Points per second.$/, '您每秒获得$1相位点。'],
    [/^Cost: (.+) points\n(.+)$/, '成本: $1 点'],
    [/^(.+)Try reloading the page, and if it don't help, contact the mod author!\n(.+)$/, '尝试重新加载页面，如果没有帮助，请联系mod作者!'],
    [/^You have (.+)Space, which are giving a (.+) boost to Time Power gain$/, '你有$1空间，将增强空间力量获取量$2'],
    [/^which are giving (.+)Space per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generators per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generator\^2s per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器^2每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generator\^3s per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器^3每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generator\^4s per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器^4每秒。\n$2成本：$3 空间力量'],
    [/^which are giving (.+)Space Generator\^5s per second.\n(.+)Cost: (.+) Space Power$/, '将生产$1空间发生器^5每秒。\n$2成本：$3 空间力量'],
    [/^Raises all non-static layers' \(that means, all layers except for Hope and Rage\) gain by \^(.+).$/, '所有非静态层级(指除了希望和愤怒以外的层级)产量变为^$1'],
    [/^which are making all Space Generators (.+)faster.\n(.+)Cost: (.+) Space$/, '将使所有发生器$1倍加速。\n$2成本：$3 空间'],
    [/^which are making all Time Multipliers (.+) cheaper.\n(.+)Req: (.+) Time Power$/, '将使全部时间加倍器便宜$1倍。\n$2成本：$3 时间力量'],
    [/^which are making all Time Multipliers and Time Boosters (.+) cheaper.\n(.+)Req: (.+) Time Boosters$/, '将使你全部时间加倍器和时间增强器便宜$1倍。\n$2成本：$3 时间增强器'],
    [/^which are boosting your point gain by (.+).\n(.+)Cost: (.+) Time Power$/, '将使你的点数获取乘以$1倍。\n$2成本：$3 时间力量'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^which are giving a ×(.+)e(.+) boost to point gain, a ×(.+)e(.+) boost to self gain and are producing (.+) Echepoints per minute.$/, '使你的点数获取×$1e$2，自身获取增加×$3e$4，每秒生产$5阶层点数'],
    [/^which are giving a ×(.+)e(.+) boost to point gain, a ×(.+)e(.+) boost to self gain and are producing (.+)e(.+) Echepoints per minute.$/, '使你的点数获取×$1e$2，自身获取增加×$3e$4，每秒生产$5e$6阶层点数'],
    [/^which are giving a ×ee(.+) boost to point gain, a ×(.+)e(.+) boost to self gain and are producing (.+) Echepoints per minute.$/, '使你的点数获取×ee$1，自身获取增加×$2e$3，每秒生产$4阶层点数'],
    [/^which are giving a ×ee(.+) boost to point gain, a ×(.+)e(.+) boost to self gain and are producing (.+)e(.+) Echepoints per minute.$/, '使你的点数获取×ee$1，自身获取增加×$2e$3，每秒生产$4e$5阶层点数'],
    [/^which are giving a ×ee(.+) boost to point gain, a ×ee(.+) boost to self gain and are producing (.+)e(.+) Echepoints per minute.$/, '使你的点数获取×ee$1，自身获取增加×ee$2，每秒生产$3e$4阶层点数'],
    [/^which will decrease your Life Power by (.+) per second but will give a ee(.+)× boost to Time Power gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的时间力量增强ee$2×(基于当前生命力量'],
    [/^which will decrease your Life Power by (.+) per second but will give a (.+)e(.+)× boost to Time Power gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的时间力量增加$2e$3×(基于当前生命力量'],
    [/^which will decrease your Life Power by (.+) per second but will give a (.+)× boost to Time Power gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的时间力量增加$2×(基于当前生命力量'],
    [/^which will decrease your Life Power by (.+) per second but will give a ee(.+)× boost to Space Power gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的空间力量增加ee$2×(基于当前生命力量'],
    [/^which will decrease your Life Power by (.+) per second but will give a (.+)e(.+)× boost to Space Power gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的空间力量增加$2e$3×(基于当前生命力量'],
    [/^which will decrease your Life Power by (.+) per second but will give a (.+)× boost to Space Power gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的空间力量增加$2×(基于当前生命力量'],
    [/^which will decrease your Life Power by (.+) per second but will give a ee(.+)× boost to point gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的点数获取增加ee$2×(基于当前生命力量'],
    [/^which will decrease your Life Power by (.+) per second but will give a (.+)e(.+)× boost to point gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的点数获取增加$2e$3×(基于当前生命力量'],
    [/^which will decrease your Life Power by (.+) per second but will give a (.+)× boost to point gain \(based on current Life Power count$/, '将会每秒消耗$1的生命力量冰使你的点数获取增加$2×(基于当前生命力量'],

]);